### ISSUE TITLE
pass instance key on tztime click events

### ISSUE THREAD

**Issue by ultrabug** [i3/i3status#10]
Hi,

Currently, when i3status passes a click event on a **tztime module** to an external program, it does not include its instance name (which is mendatory for tztime).

    {'y': 9, 'x': 2256, 'button': 1, 'name': 'tztime'}

Could you please make it so that i3status passes an `instance` key with the name of the tztime module being clicked ?

Please also make sure it does so on `time` modules with instance names.

**Comment by stapelberg** [comment]
This is confusing to me. i3status doesn’t handle clicks at all. Did you mean i3bar? If so, please file this on https://github.com/i3/i3

**Comment by ultrabug** [comment]
Stupid me, sorry : https://github.com/i3/i3/issues/1569

**Comment by ultrabug** [comment]
@Airblader @stapelberg : thx for the quick fix, would you be so kind to check also all the other modules please while we're at it ? especially the `time` one.
