### ISSUE TITLE
Add lower threshold for battery charging wattage

### ISSUE THREAD

**Issue by seidler2547** [i3/i3status#111]
For some reason the ACPI on my laptop (Sony Vaio Duo 11) often reports 0.01W of charge rate even when it's fully charged (or rather, 80% charged because of the "battery health" function). It would be great if one could define a threshold under which the battery charge/discharge rate would be considered 0. For now, whenever my battery thinks it is charging with 0.01W, the time obviously also goes awry, i.e. showing 3570:00 as remaining time.

**Comment by stapelberg** [comment]
I’m not very keen on adding functionality to i3 that only helps with individual computer models being broken in some way or another.

Maybe the ACPI kernel driver could be changed to not report this sort of minimal charging activity?

**Comment by eplanet** [comment]
Is this issue still worth being opened ? I'm afraid some people would like the ACPI kernel driver to report any charging activity, while other would like to put a threshold. Bottom line, this issue won't be fixed since it is not considered a i3status issue.

**Comment by Airblader** [comment]
Agreed, there hasn't been any further feedback, so closing.
