### ISSUE TITLE
Multiple mount point on the same disk entry

### ISSUE THREAD

**Issue by eplanet** [i3/i3status#118]
I wonder if that feature could have a chance of being merged: defining a set of mountpoint instead of only one, in order to factorize configuration definition.
For instance let's say I want to monitor available space on /, /home and /var, I'd do it that way:
```bash
disk "/ /home /var" {
        format = "%avail %path"
}
```
The output would then be:
2.5 GiB / | 90.2 GiB /home | 1.2 GiB /var

**Comment by Airblader** [comment]
Am I missing something or why can't you just use multiple `disk` blocks?

**Comment by eplanet** [comment]
The idea is precisely to avoid defining multiple disk blocks, but defining all mountpoints in one shot.
It's just a proposal. But I think I'll implement it anyway… :-)

**Comment by Airblader** [comment]
I don't really see the value in that. If you want to avoid duplication, I'd suggest writing this as a wrapper that generates the config. The blocks in the i3status config map 1:1 to blocks on i3bar's statusline, which IMHO makes a lot of sense.

@stapelberg Agreed?

**Comment by stapelberg** [comment]
I also don’t see the point. As @Airblader mentioned, blocks map 1:1, and we definitely want to keep that property. In addition, I don’t think people configure mount points often enough for easier (?) configuration to be worthwhile. For people who do, I’d recommend coming up with an abstraction (e.g. template file, shell script, macro processor, …) to generate the i3status config file.

**Comment by eplanet** [comment]
Fair enough. Thanks for the explanations.
