### ISSUE TITLE
New naming convention of udev incompatible with `ethernet _first_`?

### ISSUE THREAD

**Issue by msis** [i3/i3status#123]
The newer version of `systemd`/`udev` uses new [naming schemes](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/). Therefore, some times the Ethernet is named `enxXXXXXXXXXXXX` and is not detected by the the `ethernet _first_`.

**Comment by stapelberg** [comment]
The code (https://github.com/i3/i3status/blob/dbc59d7376dd1c49b4948d17209910fad01b3560/src/first_network_device.c) does not make any assumptions about the device names. I’m not convinced that the problem at hand is the name of the device.

Can you describe which version of i3status you’re using, what you’re seeing and what you’re expecting?

**Comment by msis** [comment]
So I'm using : 
```
i3status 2.10-19-gc094f47b4571 (2016-03-30) © 2008 Michael Stapelberg and contributors
```

When my ethernet connection is up, i.e. `ifconfig` returns an interface with the name `enxXXXXXXXXXXXX` with an IP address, `i3status` ignores it and returns `E: down`.

First I thought that it was the `path` variable limited to 1024. But I modified that on my fork and didn't seem to solve the problem. 

To make sure that interfaces is listed, I tried the example code provided through `man getifaddrs` and it lists it... and an `AF_INET`.

**Comment by Airblader** [comment]
@msis It'd be easiest if you just debug the code referenced by @stapelberg to find out at which point the entry for your interface gets skipped. A simple way would be putting `fprintf` to each `continue`, or to use `gdb`.

**Comment by msis** [comment]
Thanks guys!

After debugging, I have found out that virtual interface gets selected first before my real interfaces.

I googled around to see if there's any solution to skip virtual interfaces, and it seems that one solution would be to use the flags defined in `/usr/include/linux/if.h` and it's not good enough.
I don't know how useful it will be depending on the distrib users will be using. And also we need to rely on volatile flags, in my case `IFF_RUNNING` or `IFF_LOWER_UP` .

Do you guys have any idea how to avoid selecting a virtual interface?

**Comment by stapelberg** [comment]
Which interface specifically gets selected in your case? I.e., what’s a virtual interface?

**Comment by msis** [comment]
In the many case I tried it recently it's the docker local virtual network `docker0`.

**Comment by stapelberg** [comment]
Maybe it would make sense to start a blacklist, or fill a whitelist with device names that udev assigns to physical ethernet interfaces?

I wonder what the situation is with other virtual devices, such as these created by virtualbox. And also, I wonder about the situation with ethernet devices when i3status is running within the VM.

For now, the workaround is to hard-code your ethernet device name.

**Comment by msis** [comment]
You're right!

Can we have conditions inside the `i3status` configuration file?

**Comment by stapelberg** [comment]
We use libconfuse for configuration file parsing. As far as I’m aware, there is no support for conditionals in libconfuse.

**Comment by msis** [comment]
Alright. 
Should I close this issue or do you want to keep it for the future?

**Comment by stapelberg** [comment]
Let’s leave it open so that other users who run into the same issue can easily find it and add their comments.

**Comment by ntnn** [comment]
I'm encountering a similar issue.

I have a few VPNs I'm connecting to on tun and tap devices. When I'm on my laptop without an ethernet connection `_first_` displays the same as the first tun/tap device it finds, which can be quite annoying with longer bars.

A blacklist or similar would be great.
