### ISSUE TITLE
volume: able to specify pulse device via "pulse[:N]" or "pulse[:Name]"

### ISSUE THREAD

**Issue by ntzrmtthihu777** [i3/i3status#126]
Shouldn't be terribly hard, but to be frank I lack the c chops to do it in a way that isn't ugly as hell.

Reason: The device index is variable, whereas the device name appears to be pretty constant even across reboots and unplug/replugs.

Proof: run `pacmd list-sinks| grep -e 'card:' -e 'device.id' -e 'index:' -e 'alsa.card_name'`, unplug and replug a device and re-run it. Each time the device will increment its index.

**Comment by Watcom** [comment]
You can specify the default sink in /etc/pulse/default.pa with a line like this:
`set-default-sink alsa_output.usb-Creative_Technology_Ltd_SB_X-Fi_Surround_5.1_Pro_00000IWp-00-Pro.analog-stereo`
and then leave the device as empty or "default" in i3status.conf. Then you can unplug/replug and the device and it *should* stick with it (I haven't tried it though).

**Comment by ntzrmtthihu777** [comment]
Oh I know about that, do it a fair amount of time, but suppose one wants multiple displays of volume for multiple sound devices? Can't very well have two defaults ;)
Being able to specify an exact device by name would be very useful.

**Comment by Watcom** [comment]
Yes, that's true. I have to say it makes me cringe a little to force PulseAudio to resolve the device name once per second, so it would have to do it at startup. But then you wouldn't be able to follow the device dynamically as you replug it without restarting i3status.

**Comment by ntzrmtthihu777** [comment]
oh yeah. didn't think about that portion of it... hrm. perhaps a periodic refresh of name->index mappings outside of the 1s loop?

**Comment by Watcom** [comment]
Ideally it should subscribe to PulseAudio events so that it detects a change and only then resolve any new indices.
I'm curious about how useful this would be, though. Do you have such a setup, I mean with multiple sound cards and you actually need to see the volume of more than one simultaneously? As opposed to using one at a time and having PulseAudio decide which is the default based on what's plugged in?

**Comment by ntzrmtthihu777** [comment]
I have two main sound cards, the one on my GPU and a Logitech G933; I keep the GPU at max volume and control the actual volume on the tv I use as a display, so I'm really only interested in the headset at any given time, but I do believe this could be useful for folks with more advanced audio setups.

(I also have an on-mobo card, but I never use it, so its moot to this discussion)

**Comment by Watcom** [comment]
See, this issue has so little demand not even the requester needs it! ;)
Just kidding, it's true that using the device name makes more sense with PulseAudio since you have no control over the index and it always increments when devices change.

I haven't looked into it yet but I think the best way seems to be what I indicated, looking up the index in the beginning and updating it each time a relevant event is received.  Would this be OK, @stapelberg?

**Comment by stapelberg** [comment]
Updating the index on events sounds good to me.

But, if there is no need for this feature, why bother with it? :)

**Comment by Watcom** [comment]
Exactly, maybe we leave this open and wait for further requests of users with more use cases.

**Comment by eficker** [comment]
I request. This would clean up the use case where there are multiple audio devices. For example, on board audio, and a usb headset.

**Comment by freb** [comment]
I have this use case. I have my default audio out which is for my main speakers and then my other volume is for my headset. It's really nice to be able to see what auto percent both of my devices are at. But like the OP mentions, once I replug my headset (which I may do more frequently than most) the device I changes and I see something like the following:

![image](https://cloud.githubusercontent.com/assets/1723508/18414335/a1cb3328-7778-11e6-97e2-a6c6cb94fba2.png)

Showing 0% unless I change my config. After login it appears to keep the same ID though.

**Comment by bomis** [comment]
Likewise. have the same use case as @eficker and @freb

This would really help.

**Comment by Watcom** [comment]
Can you guys test my patch above? You may either specify the device name after "pulse:" or its (initial) index, and it should "follow" the device even after you unplug it and later plug it back in.

**Comment by freb** [comment]
I've tested it. Using the device ID appears to be working with following. This doesn't persist i3 restarts though, probably as expected.

I also confirmed you can use the device name. This was successful with the sink for my onboard audio. However, I'm getting an error when I try to use the device name of my USB headset. I get `segmentation fault (core dumped)`. But as mentioned, when I reboot and have the correct ID in i3status for my usb headset, as long as I don't reboot i3/i3status then it persists unplug/plug-ins.

After this testing, I realize that I've never been able to adjust the device ID for my USB headset in the i3status config and have it start working after restartin i3/i3status.

**Comment by Watcom** [comment]
Thanks for testing. I could not reproduce the segfault since my setup is different but I found the probable cause and fixed it. If I understand correctly you couldn't use the device name as it segfaulted? Well, It *should* work now.

**Comment by freb** [comment]
Using the device name works perfectly now. Thanks!

**Comment by auscompgeek** [comment]
Can this be closed now?

**Comment by freb** [comment]
Yes. The commits fixed the issue.
