### ISSUE TITLE
"Error: status_command process exited unexpectedly (exit 0)"

### ISSUE THREAD

**Issue by JaxtonHale** [i3/i3status#128]
I'm getting this error on i3. The bar simply does not work. I have i3status and i3-wm installed. When I type i3status in the terminal and hit enter, there is no output. 

What is the solution to this issue? I've used i3 before and the bar worked perfectly. I'm using the same i3 config as before.

**Comment by stapelberg** [comment]
What’s the result of `i3status --version`?

Can you try using the default config?

Can you attach the output of `strace -f -s 2048 -tt i3status`?

**Comment by yashar-sb-sb** [comment]
I'm having the same problem and when I run i3status by itself it outputs this:
`i3status: trying to auto-detect output_format setting`
`i3status: auto-detected "term"`
`fe80::1187:3b46:85ad:f8e2 | 639.0 GiB | W: down | E: 192.168.1.10 (100 Mbit/s) | UNK 0.00% | 0.01 | 2017-03-02 22:42:36`

It seems like it works by itself but doesn't work when it's called by i3bar!

**Comment by Airblader** [comment]
@yashar-sb-sb Please add `output_format = "i3bar"` in the `general` block of the i3status config. If the issue still persists, please run it from a terminal agan and provide that output.

**Comment by morelandjs** [comment]
I'm experiencing the same error. Relevant output of strace -f -s 2048 -tt i3status is,

13:03:14.166716 read(3, "#\n# ~/.config/i3status/config\n#\n\n# common settings for all hosts\n\ngeneral {\n  interval = 10\n  colors = true\n  color_good = \"#268bd2\"\n  color_degraded = \"#b58900\"\n  color_bad = \"#dc322f\"\n  output_format = \"i3bar\"\n}\n\ntime {\n  format = \"%a %d %b %R\"\n}\n\nload {\n  format = \"%1min %5min %15min\"\n}\n\nbattery 0 {\n  format = \"%status %percentage %remaining %consumption\"\n  last_full_capacity = true\n  threshold_type = \"percentage\"\n  low_threshold = 10\n}\n\nwireless wlp3s0 {\n  format_up = \"%essid %quality\"\n  format_down = \"wifi down\"\n}\n\norder += \"load\"\norder += \"wireless wlp3s0\"\norder += \"battery 0\"\norder += \"time\"\n", 8192) = 606
13:03:14.166749 read(3, "", 4096)       = 0
13:03:14.166773 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
13:03:14.175302 +++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

Any idea what this might be? Thanks!

**Comment by Eduruiz** [comment]
I'm stuck here too, in another issue I read the suggestion of commenting one by one of the "order" block on config to find out what is happening, with all my order block commented I keep seeing the same error.
@morelandjs, did you have any lucky with this?

**Comment by jen0vah** [comment]
Since fully updating my Arch setup I have the same problem as everyone else.

'i3status 2.11 (2017-01-21)'

**Comment by sworthiness** [comment]
I am experiencing this issue too.
I am running Arch Linux, i3bar v4.20.1, i3status v2.14

I have done the following suggestion which did not resolve the issue
> output_format = "i3bar" in the general block of the i3status config

In my case, it seems to be related to using the path_exists module, which when it fails it's check, results in the error message in i3bar but when run from xterm, it prints the format_down message with no problem.
However i have also seen segfaults from xterm too depending on what combination of path_exists and disk is used.
See segfault.txt for journal entry.
[segfault.txt](https://github.com/i3/i3status/files/8881272/segfault.txt)

**Comment by stapelberg** [comment]
@sworthiness I created https://github.com/i3/i3status/issues/489 for your specific segfault.

I’m closing this issue, because the error message can happen for a lot of different reasons. People write “I have the same problem”, but chances are you’re having a different problem that results in the same error message.

If you come across this error, start with a fresh config and copy your config over to the fresh file until i3status fails. Then possibly file a bug for the specific issue you tracked down.
