### ISSUE TITLE
Missing or broken features in 2.7?

### ISSUE THREAD

**Issue by jolenzy** [i3/i3status#131]
So I've just updated i3status to 2.7 on Gentoo, and it crashed.

Debugging showed that I had to disable the following options in my `i3status.conf` file:

Battery block:
- `format_down`
- `hide_seconds`
- `status_chr`
- `status_bat`
- ` status_full`

Volume block:
`format_muted`

**Comment by stapelberg** [comment]
Can you enable coredumps and provide a backtrace (using `backtrace full` in gdb) please?

Also, what’s the output of `i3status --version`?

**Comment by stapelberg** [comment]
Also note that the current version of i3status is 2.10. Why are you on 2.7? Which version did you use before?

**Comment by jolenzy** [comment]
Sorry, I already updated it yesterday to 2.10, and the problem is gone.
