### ISSUE TITLE
Adding S.M.A.R.T. support for disk information

### ISSUE THREAD

**Issue by eplanet** [i3/i3status#133]
I know you guys want to keep i3status very efficient and its code base small, but what do you think about adding the possibility to retrieve some information about a disk using S.M.A.R.T. monitoring system ?
This could give immediate feedback to user about his disk, such as its health, performance, temperature, error rate and many more.

**Comment by stapelberg** [comment]
I don’t think SMART fits the i3status philosophy. IMO, SMART is something which you should monitor in the background and be alerted about upcoming failures (see the smartmontools package), not something which you would look at every hour or so.
