### ISSUE TITLE
feature: aggregate representation for multiple batteries

### ISSUE THREAD

**Issue by dustymabe** [i3/i3status#138]
Some newer laptops have multiple batteries. rather than modifying the config to show both batteries it would be cool to have support (could be default behavior or non-default configurable) for showing both batteries as an aggregate. This would treat them as 1 and show the capacity of them together and the actual remaining time til power outage. 

Here is an example where someone has a manual workaround for this:
https://josiah.wordpress.com/2015/01/29/making-i3status-work-with-multiple-batteries/

Maybe we could get that type of functionality in i3 if we think it's worthy. 

Thanks for the great work!

**Comment by stapelberg** [comment]
I think it’s unfortunately not so simple to merge the status of multiple batteries.

As an example, i3status can only predict the remaining battery time by looking at the remaining capacity and the discharge rate. However, discharge rate is only reported when a battery is actually discharging, and only one battery is discharging at a time. Hence, the remaining time would never be accurate. One could make the assumption that both batteries should discharge at roughly the same rate, but I’m hesitant to hard-code that assumption into i3status, as I’m not convinced that it typically holds.

**Comment by dustymabe** [comment]
Thanks @stapelberg. That makes sense. What do you think of the way the guy is doing it in https://josiah.wordpress.com/2015/01/29/making-i3status-work-with-multiple-batteries/ by combining the uevent information from both batteries. Does his method suffer from that bad assumption?

**Comment by stapelberg** [comment]
Given that we’re talking about a rather uncommon case (the vast majority of notebooks have precisely 1 battery), I think for now I prefer to not add that complexity (both technical, and, more importantly, mental) to i3status.

**Comment by Airblader** [comment]
I +1 the request, though I agree with the issue. I also don't use i3status myself, but I have the very situation that my machine has two batteries.
