### ISSUE TITLE
Unmounted disk prints wrong information

### ISSUE THREAD

**Issue by eplanet** [i3/i3status#147]
While we can easily specify an error message (or whatever value) through `format_not_mounted` option, when we don't, random wrong values are printed for unmounted disk:
```yaml
disk "/unmounted/disk" {
    format = "unmounted/disk: %used (%avail)/ %total"
}
```
Result in:
```bash
$ ./i3status
unmounted/disk: 5.9 MiB (128.0 TiB) / 5.9 MiB
```
I think we should print empty values (or maybe "-"), when `format_not_mount` is not specified and the disk is not mounted, to end up with something like:
```bash
unmounted/disk: - MiB (- TiB)/ - MiB
```
I'd be happy to propose a PR to implement that if you agree.

**Comment by Airblader** [comment]
Makes sense to me.

**Comment by Airblader** [comment]
Just one small nit, if we do this, let's please use a typographically correct dash (»–«) and not a hyphen (»-«).

**Comment by stapelberg** [comment]
Makes sense to me as well.

**Comment by eplanet** [comment]
Closing the issue since #148 was merged.
