### ISSUE TITLE
USB built-in 3g modem incorrectly identified as the _first_ ethernet device

### ISSUE THREAD

**Issue by cakturk** [i3/i3status#152]
I have a laptop with a USB built-in 3g modem. Sometimes, i3status
identifies my 3g modem interface as the first ethernet interface. I
looked through the sources and find out that the reason is that network
interfaces are determined as wireless based on the existence of a
"_wireless_" directory inside /sys/class/net/iface directory. But It seems
my 3g modem's sysfs directory doesn't have any "_wireless_" directory.

So how about parsing _uevent_ files to detect network interface types? We
can use DEVTYPE variable to actually find out what kind of device it
really is. _uevent_ file provides us a DEVTYPE variable, whose value
is set depending on the network interface type.  Plain ethernet devices
don't have a DEVTYPE (DEVTYPE=NULL), wwan modems have DEVTYPE=wwan and
traditional wifi devices have DEVTYPE=wlan. I've forked and done a
couple of changes to the code. You can find it at https://github.com/cakturk/i3status/commit/c9154845637b7511e4c89c11d581534615dbdeed

I'd be very happy if you review my code and give feedback.

**Comment by stapelberg** [comment]
The approach seems sound. Can you send a pull request please?

**Comment by cakturk** [comment]
Hi, I've just sent you the pull request  #153

**Comment by stapelberg** [comment]
Fixed with 15de209cbaee6827f061e8d2788c9db232012c6b
