### ISSUE TITLE
Incorrect battery values for users using last full capacity with ampere to watt conversion.

### ISSUE THREAD

**Issue by tnnn** [i3/i3status#157]
After the refactoring made in d74bc90bfe8ac11ba3d6ac5326d95dedd10c39c3, the logic behind last full capacity calculation changed, breaking it for users that who were also using ampere to watt conversion.

Before the change, there was only `full_design` field. Its value was assigned depending on the `last_full_capacity` option - it was either full design or last full capacity reported. If a ampere to watt conversion was required, `full_design` was correctly converted.

However, since after the change, there are two separate fields for full design capacity (`full_design`) and last full capacity (`full_last`). Unfortunately, if an ampere to watt conversion is required, only the `full_design` gets converted. If we try to use `full_last`, the units don't match and we get incorrect results (way over 100%, which get capped at 100% battery status).

**Comment by Airblader** [comment]
Thanks for reporting. @tommie Can you please look into this?

**Comment by tnnn** [comment]
@Airblader The fix is IMHO trivial - I've added appropriate puil request.

**Comment by Airblader** [comment]
Thanks. :-)

**Comment by tommie** [comment]
Definitely an oversight on my part.
