### ISSUE TITLE
wrong height with font Cantarell

### ISSUE THREAD

**Issue by oberon2007** [i3/i3status#159]
This is probably not a bug of i3status itself, but I am hoping that you will have some helpful information for me about what is causing this problem:
With the latest update of the Archlinux **cantarell-fonts** package i3status bar apparently fails at calculating the correct height of the bar:

![](http://imgur.com/YooFFVel.png)

Now as you can see [here](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/cantarell-fonts&id=7e609f68289ab557532c40adf3ac2056821d17c3), the only change that has been applied to the font package is, that a symlink to **/etc/fonts/conf.avail/** was added that had been missing until then. Now when I remove this symlink all is well again:

![](http://imgur.com/T1ZiOS6l.png)

So it looks like the content of the linked **cantarell.conf** file is causing this failure as soon as it becomes available in **/etc/fonts/conf.avail/**.
Here's the content of the file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "../fonts.dtd">
<!--

     Define aliasing and other fontconfig settings for Cantarell.

-->
<fontconfig>
  <!-- Generic name assignment -->
  <match target="pattern">
    <test qual="any" name="family">
      <string>Cantarell</string>
    </test>
    <edit name="family" mode="assign" binding="weak">
      <string>Cantarell</string>
    </edit>
  </match>
  <!-- Generic name aliasing -->
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>DejaVu Sans</family>
    </prefer>
  </alias>
</fontconfig>
```
Thank you for your time
kind regards

Bernhard Landauer

**Comment by stapelberg** [comment]
Thanks for the detailed report. Can you please close it and open it on https://github.com/i3/i3 instead, though? i3status supplies text, i3bar (part of the i3 repository) renders it.

**Comment by oberon2007** [comment]
https://github.com/i3/i3/issues/2429
