### ISSUE TITLE
killall -USR1 i3status doesn't reload bar

### ISSUE THREAD

**Issue by edi9999** [i3/i3status#160]
When I run `killall -USR1 i3status`, my i3bar is not updated.

My version is : 

```
i3status --version
i3status 2.10 (2016-01-01) © 2008 Michael Stapelberg and contributors
```

Strangely, if I run `pactl set-sink-volume @DEFAULT_SINK@ -5%` from the commandline, the i3bar is updated.

Do you know if the signal handling works everywhere ?
What might be the reasons of the issue ?

**Comment by ixjlyons** [comment]
This was [fixed](https://github.com/i3/i3status/pull/95) pretty much immediately after 2.10 came out. I don't know when 2.11 is scheduled to be released (i3status doesn't get released very often), so you might consider building from more up-to-date source if it's an important feature.

**Comment by edi9999** [comment]
Thanks for the quick reply

**Comment by stapelberg** [comment]
Closing as it’s fixed already.

**Comment by DmitryMyadzelets** [comment]
The `killall -USR1 i3status` doesn't work again with `i3status 2.12 (2018-05-11)`.

**Comment by stapelberg** [comment]
> The `killall -USR1 i3status` doesn't work again with `i3status 2.12 (2018-05-11)`.

Please file a separate issue instead of commenting on old, possibly unrelated issues, and describe what you’re seeing/expecting.
