### ISSUE TITLE
Feature request: allow icons for more battery-states

### ISSUE THREAD

**Issue by sanderboom** [i3/i3status#161]
## Feature request: allow icons for more battery-states

**Current situation:**

AFAIK, it's possible to define icons for the following battery-states:
```
status_bat = " "
status_chr = " "
status_full = " "
```
Looking for possible icons, I turned to the often used FontAwesome iconset (http://fontawesome.io/cheatsheet/). FontAwesome offers the following interesting battery indicators: 

![screenshot at 2016-09-05 11-57-45](https://cloud.githubusercontent.com/assets/5956570/18244487/94d4a6d4-7360-11e6-9b98-ee406e8a97f2.png)

**Desired situation:**
You guessed it: it would be great if we can set icons for the whole cycle:
- empty
- quarter
- half
- three quarter
- full (already possible)

Thanks for looking into this!

Output of `i3 --moreversion 2>&- || i3 --version`:
```
λ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 1582)
```

**Comment by stapelberg** [comment]
The i3 philosophy is to use text where text has an advantage over icons. In this particular case, battery status is much more precisely communicated using text. I.e., the text “73%“ uses about as many pixels as the icons you’re talking about, yet reveals way more precise information.

For that reason (and to keep the number of options in i3status at bay), I’m declining this feature request.

That being said, if you feel strongly about this, feel free to either patch i3status yourself, or use a wrapper script which parses the text, determines the correct icon to use, and replaces text by the icon.

**Comment by geyslan** [comment]
> That being said, if you feel strongly about this, feel free to either patch i3status yourself, or use a wrapper script which parses the text, determines the correct icon to use, and replaces text by the icon.

@stapelberg Despite the i3 philosophy, the mentioned patch would be merged? If yes, I would add:

```
status_0 = ""
status_25 = ""
status_50 = ""
status_75 = ""
status_100 = ""
```

And a new option `status_by_level = no` that would use the i3 way with the actual 3 options (status_chr, status_bat, status_full) or with `yes` the new 5 options by percentage.

**Comment by Airblader** [comment]
I don't see why that proposal addresses any of the things mentioned, so no, the answer remains the same.

**Comment by al797** [comment]
As user I think this would be very nice to mix or actually replace numbers with icons, for those who don't care about strict percentage information.
Having different icons for 0, 25, 50, 75 and 100% plus the color for low_threshold is enough to let the user know about the battery status.
Adding this feature as an option to the default way wouldn't do any harm.

**Comment by Airblader** [comment]
See https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/ which was for i3, but applies to i3status just as well. The architecture explicitly allows i3status to be extended by a wrapper script or replaced by another tool if you want to do such things.
