### ISSUE TITLE
how is the wireless quality calculated / what does quality actually measure?

### ISSUE THREAD

**Issue by NullVoxPopuli** [i3/i3status#164]
title says it all. Just wondering what 100% quality would be

**Comment by Airblader** [comment]
Please use the subreddit or the mailing list for such questions. This is the issue tracker.

Anyway, you can find the code right here on Github. That tells you exactly how it's done. Make sure you're using the latest version though so you're comparing the correct code. 

https://github.com/i3/i3status/blob/master/src/print_wireless_info.c
