### ISSUE TITLE
Ethernet port wrongly detected

### ISSUE THREAD

**Issue by MartijnBraam** [i3/i3status#173]
I have a laptop without an ethernet interface, only wireless. I use a usb ethernet interface with it. If the interface is not connected then the statusbar shows me that it exists but doesn't have an IP and has a speed of 10 Mbit/s. Sometimes it correctly recognizes that i don't have ethernet and show it as down. 

Everytime the interface is actually connected the status is fine.

``` bash
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether e8:2a:ea:76:64:34 brd ff:ff:ff:ff:ff:ff
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
4: sixxs: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500
    link/none 
```

I have no idea what the next debugging step is. Do you need more information?

**Comment by eplanet** [comment]
Could you both provide what `ls /sys/class/net` outputs on your laptop, and the paragraph of your `i3status.conf` related to network interface?

**Comment by MartijnBraam** [comment]
The /sys/class/net output
```bash
ls -lah /sys/class/net
total 0
drwxr-xr-x  2 root root 0 29 okt 21:40 ./
drwxr-xr-x 52 root root 0 29 okt 09:44 ../
lrwxrwxrwx  1 root root 0 29 okt 09:44 lo -> ../../devices/virtual/net/lo/
lrwxrwxrwx  1 root root 0 29 okt 09:44 sit0 -> ../../devices/virtual/net/sit0/
lrwxrwxrwx  1 root root 0 29 okt 09:44 sixxs -> ../../devices/virtual/net/sixxs/
lrwxrwxrwx  1 root root 0 29 okt 09:44 wlp2s0 -> ../../devices/pci0000:00/0000:00:1c.3/0000:02:00.0/net/wlp2s0/
```

The config is just the defaults:


```
order += "ethernet _first_"

ethernet _first_ {
        # if you use %speed, i3status requires root privileges
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

```

**Comment by eplanet** [comment]
In any case if you're using wireless, you should definitely prefer [`wireless _first_`](https://github.com/i3/i3status/blob/master/i3status.conf#L22) configuration. Maybe that could explain the erratic behavior you are witnessing.

**Comment by MartijnBraam** [comment]
I'm using both wireless and wired. Sometimes at the same time.

**Comment by eplanet** [comment]
@MartijnBraam : can you confirm if #219 fix your problem?
