### ISSUE TITLE
FreeBSD: Ethernet port without link shown as UP.

### ISSUE THREAD

**Issue by xkpd3** [i3/i3status#176]
Hello,
I'm running FreeBSD 11.0-RELEASE.

My ethernet device is alwasys shown as "UP", even when no cable is plugged in.

```
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4019b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,VLAN_HWTSO>
	ether b8:8a:60:de:c4:1b
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: no carrier
```

If I manually set it to down, it works. The behavior is different for my wireless devices and also for the ethernet device on linux.

My i3status.conf:
```
order += "ethernet em0"
ethernet em0 {
        format_up = "ETH"
        format_down = "NO ETH"
}
```

Best Regards,
Stefan

**Comment by stapelberg** [comment]
Which version of i3status are you using?

cc @bsdjhb @bapt

**Comment by bapt** [comment]
Using the latest from ports I cannot reproduce the issue on freebsd 11 or 12 using the latest released version I also have an em0

**Comment by xkpd3** [comment]
I'm using i3status version 2.10 (latest in 11-release).
I just compiled the latest version (i3status 2.10-66-gbe87c5a) and got the same result.

I've attached a short video.
[i3status.zip](https://github.com/i3/i3status/files/587707/i3status.zip)

**Comment by xkpd3** [comment]
I found the issue. Not an issue actually - more an inconsistency between how wireless and ethernet is handled.

There are 3 color states: good, degraded, bad
There are two text formats: format_up, format_down

If ethernet has an IP address:
- color: good
- text: format_up

If ethernet has no IP address:
- color: degraded
- text: format_up

If ethernet cable is unplugged:
- color: degraded <-- why not bad?
- text: format_up <-- why not down?

If wireless has is associated with an access point (with IP):
- color: good
- text: format_up

If wireless has is associated with an access point (no IP):
- color: degraded
- text: format_up

If wireless has is not associated with an access point:
- color: bad
- text: format_down

I think eth0 without link should show format_down and color bad.
I also think a format_degraded would also be cool :)

The use-case I'm trying to accomplish:

My status bar should always look like this. Format_up and _down are the same (I work with color):
WIFI | ETH | 192.168.0.206

WIFI comes from the wireless device
ETH comes from the ethernet device
The IP address comes from my lagg0 device, which has ETH as master and WIFI as failover device.

Based on the color of WIFI and ETH, I can see if my master and slave devices for the IP shown are active. I assume that there is a color change when a cable is plugged in or removed. This is not happening right now.

**Comment by xkpd3** [comment]
No more comments? Is my assumption wrong and it works as designed?

```
If ethernet cable is unplugged:

color: degraded <-- why not bad?
text: format_up <-- why not down?
```

**Comment by Airblader** [comment]
I haven't verified, but what you describe makes sense to me. Assuming @stapelberg agrees, PRs are always welcome.

**Comment by bapt** [comment]
Would be intrusive to differenciate. The code assumes exactly the behaviour @xkpd3 is speaking about.
It does not check if the iface is physically up or down to actually chose format on/off but rather on the system getifaddrs to be able to provide return an IP or not.

If one wants to fix, format up/down should be modified to only check the physical state of the iface (and not depend on get_ip_addr()

For the degraded part of it, the current situation sounds ok to me

**Comment by stapelberg** [comment]
Thanks for describing the inconsistency. To me, the current behavior for ethernet devices makes sense — the device is UP, but not RUNNING (in linux terminology, not sure if that transfers to FreeBSD), hence it uses format_up. Link state is visible by differentiating the good/degraded color.

I think if we want to make a change here, we should change the wifi indicator to behave the same way. I.e., no longer treat unassociated as bad, but rather as degraded, and use format_up.

I could imagine that the change in behavior is unwelcome for some users, though, so I’m not advocating for such a change. Perhaps this inconsistency is just a limitation of i3status that we need to live with.

**Comment by bapt** [comment]
We could reduce the "inconsistency" on freebsd but that would be intrusive in the code, I'm unsure how that new code could be used on linux

**Comment by xkpd3** [comment]
@stapelberg Okay, this makes sense. But thinking about the definition if UP and RUNNING doesn't hold true on a broader view. I shifts the problem to the wireless device.

The wireless device is associated without IP and therefore shown as "degraded". This is correct when looking only at the wireless device. But what if the device belongs to a bridge or a lagg (failover) device that carries the IP for it? This is what I do and what seems to be best practice in FreeBSD on Laptops to be able to switch between wifi and ethernet without loosing connection (Example 3.30: https://www.freebsd.org/doc/handbook/network-aggregation.html).

In this case the the wireless device will never be shown as good even it is UP and RUNNING perfectly fine.

I'm now working around this issue with the %ssid and the %speed indicators. They're effectively showing the information I want. Once the speed is shown, an ethernet link is present. Once an ssid is shown, the wifi is ready.

**Comment by stapelberg** [comment]
i3status doesn’t handle bridges/aggregation/more advanced networking features at all currently, as you have noticed :). Patches to improve this situation in a backwards-compatible way are welcome, perhaps by adding a new module to print network devices (as opposed to ethernet and wireless deviced specifically).

Or perhaps, if this logic is too complicated, it should go into a different tool than i3status, which tries to stay quite minimal.

**Comment by xkpd3** [comment]
Okay, that's fair. I was fiddling around a bit more and thought an additional module covering bridge/lagg ports.

```
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether b8:8a:60:de:c4:1b
	inet 192.168.0.21 netmask 0xffff0000 broadcast 192.168.255.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: active
	groups: lagg 
	laggproto failover lagghash l2,l3,l4
	laggport: em0 flags=5<MASTER,ACTIVE>
	laggport: wlan0 flags=0<>
```

So that I can configure "lagg0" and would have %activedev / %availabledev indicators that would show me which device is currently in use and which devices are available.

But this would be a nice feature, but I'm also able to implement this via script.

I think it doesn't make sense to keep this issue open any longer. Thank you for your explanations.
