### ISSUE TITLE
Provide format_bellow_threshold and format_above_threshold for disk monitor

### ISSUE THREAD

**Issue by gfa** [i3/i3status#177]
Hello

I'd like to have the possibility to configure different format for disk output depending if the disk is above or bellow threshold, my goal here is not to have output when the free space is above but a big fat red warning when the free space is bellow threshold.

I do the same for my nic in this way

ethernet enp0s25 {
        # if you use %speed, i3status requires root privileges
        format_up = "E: %ip (%speed)"
        format_down = ""
}

when it is down (normal) it doesn't print anything, but when the nic is in use it prints its status

thanks!

**Comment by stapelberg** [comment]
This makes sense to me, pull requests welcome.

We probably should implement such an option for all modules which offer configurable thresholds.

**Comment by eplanet** [comment]
@gfa if you're not willing to work on this, I'd be happy to come up with a PR.

**Comment by gfa** [comment]
@eplanet please do, thanks

**Comment by eplanet** [comment]
Should be closed since #179.
