### ISSUE TITLE
Wrong battery capacity

### ISSUE THREAD

**Issue by ael-code** [i3/i3status#186]
version: 
`i3status 2.10 (2016-01-01) © 2008 Michael Stapelberg and contributors`

here you can see the real uevent properties of my battery:
```
$ cat /sys/class/power_supply/BAT0/uevent

POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Unknown
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=14800000
POWER_SUPPLY_VOLTAGE_NOW=14526000
POWER_SUPPLY_POWER_NOW=0
POWER_SUPPLY_ENERGY_FULL_DESIGN=38920000
POWER_SUPPLY_ENERGY_FULL=25500000
POWER_SUPPLY_ENERGY_NOW=8300000
POWER_SUPPLY_CAPACITY=32
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=42T4977
POWER_SUPPLY_MANUFACTURER=SMP
POWER_SUPPLY_SERIAL_NUMBER=  973
```
But i3status is reporting `21.33%`

Where is this number taken from?

**Comment by stapelberg** [comment]
I don’t have the time to go through it for you, but https://github.com/i3/i3status/blob/master/src/print_battery_info.c#L112 is the code in question if you want to read it :).

**Comment by ael-code** [comment]
yeap I'm looking it. You don't use the `POWER_SUPPLY_CAPACITY` provided by the kernel, instead you derivate it from other value. I will try to understand were is the error.
But there is one main question: is there any reason not to use the value provided by the kernel?

**Comment by ael-code** [comment]
I mean if we have the i3status option `integer_battery_capacity = true` we should use that value

**Comment by ael-code** [comment]
oke I understood.
Since `last_full_capacity` is set to false by default, the value used in the calculus was `POWER_SUPPLY_ENERGY_FULL_DESIGN` instead of `POWER_SUPPLY_ENERGY_FULL`.
The option is documented in the man, thus sorry for the useless issue :)
