### ISSUE TITLE
use `last_full_capacity` by default

### ISSUE THREAD

**Issue by ael-code** [i3/i3status#187]
From the i3status man
> If you want to use the last full capacity instead of the design capacity (when using the design capacity, it may happen that your battery is at `23%` when fully charged because it’s old. In general, I want to see it this way, because it tells me how worn off my battery is.), just specify `last_full_capacity = true`

At the moment the `last_full_capacity` option is set to `false` by default.

From the linux kernel documentation:
> `CHARGE_FULL`, `CHARGE_EMPTY `- These attributes means "last remembered value of charge when battery became full/empty". It also could mean "value of charge when battery considered full/empty at given conditions (temperature, age)". I.e. these attributes represents real thresholds, not design values.

So in the kernel code the design values are considered not REAL thresholds, in fact they are providing an property `POWER_SUPPLY_CAPACITY` that represent the current battery percentage with integer precision that respect the REAL thresholds and not the design ones.

My proposal is to set the default value of  `last_full_capacity` to true in order to provide the REAL capacity of the battery in the default configuration.

**Comment by stapelberg** [comment]
The rationale behind using `last_full_capacity=false` is that this will allow you to see how well your battery is doing over time. Usually, notebook batteries start out a little over 100% when you buy them, and then degrade slowly over the years.

If the behavior doesn’t suit you, and/or doesn’t work on your hardware, just change the option. I’m not convinced changing the default is advisable at this point — it would change the values which lots of users see.

**Comment by tbm** [comment]
I know this is an old issue but I'm also for changing the default.  I just got a new laptop and it shows 95% full.  acpi shows 100% full.

If a new laptop is at 95%, I'd argue that CHARGE_FULL_DESIGN isn't very useful.

And on my old laptop I see 40.43% when it's full.  Sure, it's useful to see how the battery degrades.  But as it degrades, it's also hard to remember what percentage means full.  It was ~45 recently. Now it's ~40.  In a few weeks it might be ~35... hard to remember.  100% would be much clearer...

**Comment by jpmorris** [comment]
this should stay as is.  If your laptop is very old and you can't remember whehter 40 or 45 refers to a 'full' charge then rely on the %emptytime% (which is also chargingtime.  Clearly the default supplies more inforation for more cases than changing the default.
