### ISSUE TITLE
time remaining moves in and out of existence on full battery

### ISSUE THREAD

**Issue by yorickvP** [i3/i3status#191]
I have the following setting in my config:
```
battery 0 {
        format = "%status %percentage %remaining"
}
```
This works fine, but when my battery is full, toggles between `FULL 100.00% 00:00:00` and `FULL 100.00%`

(i3status 2.10)

**Comment by eplanet** [comment]
Could you copy/paste the content of your uevent file (ex: `/sys/class/power_supply/CMB1/uevent`), in both cases: when it displays the empty time and when it doesn't ?

**Comment by yorickvP** [comment]
when it's there:
```
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7600000
POWER_SUPPLY_VOLTAGE_NOW=8729000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=7894000
POWER_SUPPLY_CHARGE_FULL=7894000
POWER_SUPPLY_CHARGE_NOW=7894000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_CAPACITY_LEVEL=Full
POWER_SUPPLY_MODEL_NAME=DELL TP1GT61
POWER_SUPPLY_MANUFACTURER=SMP
POWER_SUPPLY_SERIAL_NUMBER=1xxx
```

when it's not:
```
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Full
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7600000
POWER_SUPPLY_VOLTAGE_NOW=8728000
POWER_SUPPLY_CURRENT_NOW=1000
POWER_SUPPLY_CHARGE_FULL_DESIGN=7894000
POWER_SUPPLY_CHARGE_FULL=7894000
POWER_SUPPLY_CHARGE_NOW=7894000
POWER_SUPPLY_CAPACITY=100
POWER_SUPPLY_CAPACITY_LEVEL=Full
POWER_SUPPLY_MODEL_NAME=DELL TP1GT61
POWER_SUPPLY_MANUFACTURER=SMP
POWER_SUPPLY_SERIAL_NUMBER=1xxx
```

**Comment by eplanet** [comment]
Great! This only difference lies in the values from `POWER_SUPPLY_VOLTAGE_NOW`. The issue is absent from `master` branch but actually present in `2.10`.

The source [src/print_battery_info.c](https://github.com/i3/i3status/blob/master/src/print_battery_info.c) has been deeply refactored by @tommie since, probably for the best! I can only recommend to upgrade to the very last version of i3status if you're annoyed, but the issue seems fixed to me.

**Comment by yorickvP** [comment]
Thanks! I upgraded, now I'm annoyed by the blank padding on the wireless quality display, but I removed the space in front of it since I never get 100%. It might be good to release a new version soon, otherwise distro's won't upgrade.

**Comment by dedeibel** [comment]
I know this is closed and it is fine but I wanted to add some info for people finding it.

I have the same issue but maybe another source of the problem. On my system more than ``POWER_SUPPLY_VOLTAGE_NOW`` changed. ``POWER_SUPPLY_VOLTAGE_NOW`` is occasionally zero.

```
POWER_SUPPLY_NAME=BAT0						POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Charging					POWER_SUPPLY_STATUS=Charging
POWER_SUPPLY_PRESENT=1						POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion					POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0					POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=10800000			POWER_SUPPLY_VOLTAGE_MIN_DESIGN=10800000
POWER_SUPPLY_VOLTAGE_NOW=12373000			      |	POWER_SUPPLY_VOLTAGE_NOW=12411000
POWER_SUPPLY_POWER_NOW=0				      |	POWER_SUPPLY_POWER_NOW=4703000
POWER_SUPPLY_ENERGY_FULL_DESIGN=99470000			POWER_SUPPLY_ENERGY_FULL_DESIGN=99470000
POWER_SUPPLY_ENERGY_FULL=94760000				POWER_SUPPLY_ENERGY_FULL=94760000
POWER_SUPPLY_ENERGY_NOW=94200000				POWER_SUPPLY_ENERGY_NOW=94200000
POWER_SUPPLY_CAPACITY=99					POWER_SUPPLY_CAPACITY=99
POWER_SUPPLY_CAPACITY_LEVEL=Normal				POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=45N1779					POWER_SUPPLY_MODEL_NAME=45N1779
POWER_SUPPLY_MANUFACTURER=SANYO					POWER_SUPPLY_MANUFACTURER=SANYO

```
