### ISSUE TITLE
feature request: DPI support, a la i3/i3bar

### ISSUE THREAD

**Issue by nmschulte** [i3/i3status#192]
While it's not quite clear to me what the intended DPI / HiDPI-screen related support in i3 / i3bar / ... is, I'd like to have it for i3status as well.

At the moment, I think things like padding/spacing (border widths?) and font-sizes apply.

I am still doing more playing w/ the X.org stack and the various DPI-related configuration bits to understand what the intended behavior of the various bits is; it's not very clear at the moment, and thus it's hard to say whether or not i3 / i3bar are behaving properly yet or not.

**Comment by stapelberg** [comment]
i3status provides blocks of text, it doesn’t do presentation of said text. Why do you think i3status needs to be changed for hidpi support? I’m using it for years on a hidpi display.

**Comment by nmschulte** [comment]
I was confused as to how X's DPI settings work.  Telling X about the proper size of my display w/ `DisplaySize` in a monitor section for the device seems to have got me back, and now `Xft.dpi` can be used to change scale (for most apps; urxvt doesn't seem to scale fonts).

**Comment by nmschulte** [comment]
Okay, I had a chance to figure this out finally: I was using a `font ..` line w/ a pixel value as the size; `font pango:monospace 11px`, and i3 and friends were respectfully obeying it.
