### ISSUE TITLE
external script breaks colors and separator_symbol

### ISSUE THREAD

**Issue by aleprovencio** [i3/i3status#193]
Following the docs I tried to put an external script to show `ncmpcpp's` current track, which does work fine, but as a consequence I loose the colors defined on `i3status.conf` and the `separator_symbol` config defined on `i3/config`. External script code:

    #!/bin/sh

    i3status --config ~/.i3/i3status.conf | while :
    do
      read line
      playing="$(ncmpcpp --current-song='%a - %t' 2>/dev/null)"
      echo " $playing | $line" || exit 1
    done

**Comment by stapelberg** [comment]
Quote from the (same?) docs:

> Note that if you want to use the JSON output format (with colors in i3bar), you need to use a slightly more complex wrapper script. There are examples in the contrib/ folder, see http://code.i3wm.org/i3status/tree/contrib

The correct URL is https://github.com/i3/i3status/tree/master/contrib.
