### ISSUE TITLE
Memory usage in i3status?

### ISSUE THREAD

**Issue by NickeZ** [i3/i3status#194]
Hey, Since you are unwilling to add memory usage to i3status could you at least recommend some useful alternative? I need to know how much memory I have before spinning up new virtual machines otherwise I will have an unresponsive system for the next 10-20 minutes. (I guess this is due to swapping kicking in and the load goes through the roof)

**Comment by Airblader** [comment]
i3blocks

Closing since there's no issue here, but of course everybody can keep commenting.
