### ISSUE TITLE
[FreeBSD] Volume update interval

### ISSUE THREAD

**Issue by xkpd3** [i3/i3status#196]
@bapt This is probably for you...

In Linux, the volume section ignores the the i3status update interval. I don't know how it is done, but once I increase or decrease the volume, i3status updates instantly. This is cool.

In FreeBSD this is not the case. The i3status sticks to the update interval. This is not so cool.

My volume configuration on FreeBSD looks like this:
```
volume master {
        format = "♪ %volume"
        format_muted = "(♪) %volume"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}
```

Is an instant volume update not possible / not implemented for FreeBSD, or am I doing it wrong?

Best Regards,
Stefan

**Comment by Watcom** [comment]
It only updates instantly if you use PulseAudio. But you can sort of emulate this behaviour without PulseAudio by generating a USR1 signal each time you change the volume. Example: `killall -s USR1 i3status`

**Comment by xkpd3** [comment]
Perfect! Thanks for the explanation.

**Comment by xkpd3** [comment]
Unfortunately `killall -s USR1 i3status` has no effect. But I keep the ticket closed because you explained what it's not working. Maye I start using pulseaudio. I never looked into it.

**Comment by Watcom** [comment]
Sorry, I forgot to mention. If you are using i3status 2.10 make sure you either use the latest version from github or downgrade it to an earlier (say, 2.9), otherwise the USR1 signal will not work.

**Comment by distefam** [comment]
It still works, just use the following command: `pkill -SIGUSR1 i3status`
