### ISSUE TITLE
Feature Request: show_cpu support for multi-cpu/multicore systems

### ISSUE THREAD

**Issue by beeblebrox** [i3/i3status#199]
Thanks for the great work on the i3* line. 

Would it be possible to put multicore/cpu support on the roadmap for i3status? A configuration such as "cpu_usage all", "cpu_usage 0", cpu_usage 1", etc. would be nice, but I could see extending the formatter to accept something similar to %cpu<N>.

**Comment by Airblader** [comment]
There's no such thing as a roadmap. We discuss whether a feature would be accepted and then wait for anybody to implement it. :-)

**Comment by beeblebrox** [comment]
Makes sense, would such a feature be accepted?

**Comment by eplanet** [comment]
That feature totally make sense to me, I'm even surprised nobody has ever come along with it until now… If you are not willing to implement it, I'd happily propose a PR.

**Comment by Airblader** [comment]
I agree that it makes sense. But the decision is up to @stapelberg.

**Comment by eplanet** [comment]
@Airblader: of course ;-)

**Comment by beeblebrox** [comment]
@eplanet If you want to propose the PR don't let me get in your way, it is much appreciated. 

Unfortunately, even though this seems fairly straightforward I don't have the spare time needed to accomplish this; I would do it otherwise.

**Comment by stapelberg** [comment]
The feature seems fine to me, pull requests welcome.

**Comment by eplanet** [comment]
This issue can be closed now thanks to #209.
