### ISSUE TITLE
[enhancement] sep_block_width

### ISSUE THREAD

**Issue by Airblader** [i3/i3status#20]
i3status should support changing the `sep_block_width` property in its config:

````
general {
    sep_block_width = 9
}
```

**Comment by stapelberg** [comment]
Why? I don’t want to make i3status 100% theme-able and this sounds like something that third-party status bar programs can easily add since they’re intercepting the i3status output anyway.

**Comment by Airblader** [comment]
Yeah, see my comment on the PR for this. I wanted to wait for feedback before closing it, though.
