### ISSUE TITLE
Silent failure of disk option

### ISSUE THREAD

**Issue by ALeleT** [i3/i3status#200]
I've been using i3status provided by the archlinux community repo for over a year now.  I've had an unchanged setup where my status bar reports the disk usage of my root and home partitions.  

I have a system that uses lvm for root and home and since the update from 2.10-1 to 2.11-1 the disk option for my home partition has begun to produce no output. 

This pastebin is a link to my i3status.conf
http://pastebin.com/iCt9rh0N

I'm getting no errors and have no previous problems with i3status so I'm at a loss as to how to fix this problem.

**Comment by stapelberg** [comment]
Can you run `strace -o /tmp/strace.log -f -s 2048 -v i3status` and cancel the command after a few seconds. Then, attach /tmp/strace.log please.

**Comment by ManfredGahr** [comment]
I had the same problem here, after playing with my config and removing the trailing "/" at the end of the mountpoint everything is working again.
e.g.
`disk "/home/" {...}`
becomes 
`disk "/home" {...}`

**Comment by vnctdj** [comment]
I can reproduce this issue.

@stapelberg :
[strace.log.txt](https://github.com/i3/i3status/files/764392/strace.log.txt) (added ".txt" extension to bypass GitHub annoyance)

@ManfredGahr :
Your workaround doesn't work for me.

**Comment by enriquevp** [comment]
Same as @vnctdjm , @ManfredGahr 's workaround doesn't work for me either.

[strace.log.txt](https://github.com/i3/i3status/files/767490/strace.log.txt)

**Comment by stapelberg** [comment]
I think what people are running into here is the new code which was added in commit e70ea4247fd9eefcdd3f80fdc8a045257d196fcb (cc @chrko).

The code checks `/etc/mtab` (usually a symlink to `/proc/self/mounts`) to see if a mount point with the specified path exists.

Since mount points do not have a trailing slash, this explains why removing the slashes fixes the issue for some people (pull requests welcome to ignore the slashes in i3status).

@enriquevp In your strace, I don’t see `/home/enrique` in `/etc/mtab`. I do see `/home`, however. The `disk` i3status module expects the path to a mount point, not the path to a directory (as described in https://i3wm.org/i3status/manpage.html#_disk). If you wish to use a directory, consider using `format_not_mounted`.

**Comment by Airblader** [comment]
I think we should just sanitize a trailing `/` for the user.

**Comment by stapelberg** [comment]
Isn’t that what I wrote? :)

**Comment by Airblader** [comment]
Yeah, totally overlooked those `(…)`. :-)

**Comment by dardevelin** [comment]
Hello just noticed the same issue. I have /home mounted and the trick to remove the trailling / doesn't seem to work for me.

**Comment by stapelberg** [comment]
@dardevelin What does `cat /etc/mtab` return?

**Comment by dardevelin** [comment]
@stapelberg you can find it here https://gist.github.com/dardevelin/ec9b1676539794d6d2c2d591b809a8df

**Comment by stapelberg** [comment]
@dardevelin Can you run `strace -o /tmp/strace.log -f -s 2048 -v i3status` and cancel the command after a few seconds. Then, attach /tmp/strace.log please.

**Comment by dardevelin** [comment]
@stapelberg here is the strace.log as requested https://gist.github.com/dardevelin/7fe1b23c90406412c8dd405cd73ded76

**Comment by stapelberg** [comment]
@dardevelin In that strace, you have `/home/` in your config. Remove the trailing slash and provide a new strace if the problem persists.

**Comment by dardevelin** [comment]
@stapelberg that was the very first thing I did before commenting which I did mention on the original comment. Since I notice it did nothing reverted the configuration to it's original state.

new strace no /
https://gist.github.com/dardevelin/7813c05b0a90145235af5caa09e64e34

**Comment by stapelberg** [comment]
In the new strace you only changed the “order” directive, not the “disk” configuration block. Please replace all occurrences of /home/ with /home. Use your text editor’s search and replace feature.

**Comment by dardevelin** [comment]
@stapelberg shout I must have been blind. I completely forgot that I had written disk "/home/" at the end of my config file as well. Sorry about that. Is just that the error had persisted when I attempted to copy my 'old' default' one. nice catch. Yes removing the trailing does work if of course applied to both places.

**Comment by farzadmf** [comment]
Hi, it seems to be happening to me despite having `/home` (no trailing slashes). The `/` works fine, but I don't see `/home`

I included my `strace.log` in case it's useful
[strace.log](https://github.com/i3/i3status/files/7686516/strace.log)

**Comment by stapelberg** [comment]
```
"# i3status configuration file.\n# see \"man i3status\" for documentation.\n\n# It is important that this file is edited as UTF-8.\n# The following line should contain a sharp s:\n# \303\237\n# If the above line is not correctly displayed, fix your editor first!\n\ngeneral {\n        colors = true\n        interval = 5\n        color_good = \"#2AA198\"\n        color_bad = \"#586E75\"\n        color_degraded = \"#DC322F\"\n}\n\n# order += \"ipv6\"\norder += \"cpu_usage\"\norder += \"disk /\"\n# order += \"disk /home\"\norder += \"wireless _first_\"\norder += \"ethernet _first_\"\norder += \"battery all\"\n# order += \"load\"\norder += \"memory\"\norder += \"tztime local\"\n\ncpu_usage {\n        format = \" cpu  %usage \"\n}\n\nload {\n        format = \" load %1min \"\n        # max_threshold = 0.3\n}\n\ndisk \"/home\" {\n        # format = \" hdd %avail \"\n        format = \" \342\233\201 %avail \"\n}\n\n# ethernet _first_ {\n# # if you use %speed, i3status requires root privileges\n#         format_up = \" lan: %ip %speed \"\n#         format_down = \" no lan \"\n# }\n\nbattery all {\n        # format = \"%status %percentage %remaining %emptytime\"\n        format = \" %status %percentage\"\n        format_down = \"No battery\"\n        last_full_capacity = true\n        integer_battery_capacity = true\n        # status_chr = \"\357\207\246\"\n        status_chr = \"\342\232\241\"\n        # status_bat = \"bat\"\n        # status_bat = \"\342\230\211\"\n        status_bat = \"\357\210\223\"\n        # status_unk = \"?\"\n        status_unk = \"\"\n        # status_full = \"\"\n        status_full = \"\342\230\273\"\n        low_threshold = 15\n        threshold_type = time\n}\n\nmemory {\n        format = \"%used | %available\"\n        threshold_degraded = \"1G\"\n        format_degraded = \"MEMORY < %available\"\n}\n\ntztime local {\n        format = \"%Y-%m-%d %H:%M:%S\"\n        # format = \" %d.%m. %H:%M \"\n}\n"
```

In the above config, the `order += "disk /home"` line is commented out: `order += \"disk /\"\n# order += \"disk /home\"\n`

Likely it’ll work once you fix your config file.

**Comment by farzadmf** [comment]
Wow, thank you @stapelberg , I didn't look at a few lines above what I'm changing :man_facepalming:
