### ISSUE TITLE
crashes on pulseaudio restart

### ISSUE THREAD

**Issue by emdete** [i3/i3status#220]
when restarting the pulseaudio daemon i3status terminates. console shows:

```
Assertion 'c->defer_event == e' failed at pulsecore/socket-client.c:170, function connect_defer_cb(). Aborting.
Aborted
```

**Comment by Airblader** [comment]
I wonder if this is really an i3status problem or rather a pulse problem? The assertion seems to come from pulse itself.

**Comment by emdete** [comment]
yes, i assume so as well. but it may well be a wrong usage of the API? i looked into the code but i'm not an pulseaudio expert ...

**Comment by Watcom** [comment]
Couldn't reproduce this, tried PulseAudio 8 and 10. What versions of i3status and PulseAudio are you using?

**Comment by emdete** [comment]
i have installed

- i3status-2.11_1
- pulseaudio-10.0_2

**Comment by emdete** [comment]
oups, i retested (got new pa versions today) and the problem is gone. so Airblader was probably right... i'll close the issue.
