### ISSUE TITLE
Use MemAvailable to display avaiable memory

### ISSUE THREAD

**Issue by flammi** [i3/i3status#221]
Hi folks,

I know that the display of memory usage has already been discussed here a while ago. I am asking again, because I think one key assumption Stapleberg mentioned in the manpage doesn't hold true anymore...

> Let’s talk about memory usage specifically. It is hard to measure memory in a way which is accurate or meaningful. An in-depth understanding of how paging and virtual memory work in your operating system is required. Furthermore, even if we had a well-defined way of displaying memory usage and you would understand it, I think that it’s not helpful to repeatedly monitor your memory usage. One reason for that is that I have not run out of memory in the last few years. Memory has become so cheap that even in my 4 year old notebook, I have 8 GiB of RAM. Another reason is that your operating system will do the right thing anyway: Either you have not enough RAM for your workload, but you need to do it anyway, then your operating system will swap. Or you don’t have enough RAM and you want to restrict your workload so that it fits, then the operating system will kill the process using too much RAM and you can act accordingly.

1) On the recent versions of Linux a meaningful way for measuring available memory now exists with "MemAvailable" in /proc/meminfo

2) I claim, that there are a few use cases, where the information how much memory is available (in the sense, that the linux kernel can assign it to address space of a running process), is nice to have... At first if you have a setup with multiple virtual machines or second when you have a process that really needs a large amount of RAM. I triggered the second case a while ago, while I was running a model checking tool for a university project caused my system to run short of memory... The out of memory killer needed ages and my system was not behaving well for a minute or so... A indicator that indicated the problem a few minutes before the crash would have been handy there...

Are you willing to discuss about this feature one more time and accept a pull request for that? ;-)

**Comment by Airblader** [comment]
The decision and argument is still the same as in #165. I don't think there's any new argument here that hasn't been covered before. There's also plenty ways to get this information into i3bar with other tools.
