### ISSUE TITLE
Reading small integers?

### ISSUE THREAD

**Issue by itdaniher** [i3/i3status#222]
Working to build an i3status config for a messy kernel that uses small integers where the sysfs API should use integers*1000, so the division by 1000 floors the numbers to zero. Is there any way to deal with this in i3status proper, or do I need to drop Python / bash?

Thanks!

**Comment by itdaniher** [comment]
short-term crude fix for my uses at http://sprunge.us/CYgN

**Comment by eplanet** [comment]
I suppose we should close that issue since it seems unlikely you're going to work on it?

**Comment by Airblader** [comment]
Yeah, I think we can close this. The way I understand it, the issue here lies in a broken kernel anyway. Feel free to follow up though if we need to reopen.
