### ISSUE TITLE
Time doesn't update with system time

### ISSUE THREAD

**Issue by tejaswidp** [i3/i3status#223]
I use a dual boot system and sometimes have to update the time over the network. i3status doesn't update the time after this fact. Is there something that I can do to get i3status to update instead of restarting i3wm.

**Comment by eplanet** [comment]
Hi @tejaswidp and thanks for reaching. Could you add some details about the command / service you use to update the time over the network? Also add some useful information such as both your operating system and `i3status` versions, and your `i3status` configuration file?

**Comment by tejaswidp** [comment]
I use ntpdate on ubuntu 16.04. 
The version of i3status I use is 2.10.
[Here's](https://gist.github.com/tejaswidp/ff3a6519613eebafbf25c20b17dfbc38) my i3status config.

**Comment by eplanet** [comment]
Considering [CHANGELOG](https://github.com/i3/i3status/blob/master/CHANGELOG#L1-L28) for release `2.11` there's very little chance that it would fix your issue, but could you nevertheless test on latest version? Thanks!

**Comment by honza** [comment]
I'm also affected by this. I'm using latest master.

**Comment by honza** [comment]
I'm working on putting together a minimal reproduction case, and if I only include the time in the status, then the time is kept perfectly.

**Comment by honza** [comment]
It appears that one of my scripts that places some information into the status bar takes longer to execute than the refresh interval.

**Comment by eplanet** [comment]
That is very interesting @honza! @tejaswidp: Is anything besides time updated in your status bar? Maybe the status bar is just frozen on the update.

Could you try running it from command line to see if it reproduces the issue? Also, that would be awesome if you could attach your `i3status.conf`, just in case.

**Comment by tejaswidp** [comment]
@eplanet The time shown in the command line by i3status is correct. I've posted my i3status config file above.

**Comment by domenkozar** [comment]
it's very easy to reproduce this with systemd: `$ timedatectl set-timezone Canada/Eastern`

The time will change only when you refresh/restart i3.

**Comment by eplanet** [comment]
Hello @domenkozar and thanks for the update, it made the debug very easy. Moving the `tzset()` syscall outside a condition made it work in #253. Could you try it out? Thanks!

**Comment by domenkozar** [comment]
I can confirm it fixes my timezone issue, but not sure it covers the other two cases.
