### ISSUE TITLE
i3status fails after a few minutes running (probably pulseaudio/ALSA related?)

### ISSUE THREAD

**Issue by mig1984** [i3/i3status#228]
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 1214)o abort…)
Loaded i3 config: /home/mig/.i3/config (Last modified: Thu 20 Oct 2016 11:41:51 AM CEST, 20491084 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /usr/bin/i3

**What I did:**
It usually happens after a few minutes. i3status exits with this message:

Assertion 'c->callback' failed at pulsecore/socket-client.c:126, function do_call(). Aborting.

It seems like a pulseaudio related error - there's no pulseaudio running on my laptop.
This behaviour has started about three months ago.

This is the only sound related thing which I use in the i3config - but it works well when the i3status is alive (uses ALSA):

volume master {
  format = " [VOL %volume]"
  format_muted = " [VOL off]"
  device = "default"
  mixer = "Master"
  mixer_idx = 0
}

**Comment by Airblader** [comment]
Can you report this against pulse as well? i3status is not multithreaded and since it generally works for other people I assume we're not using the API incorrectly either. Input from pulse would probably be helpful.

**Comment by mig1984** [comment]
"Unfortunately" after today's update the i3status does not fail anymore (I use the Arch Linux). Probably the reason was elsewhere than in the i3status.
