### ISSUE TITLE
i3status is great , is ther any way to add underline colorization for active workspace, like in polybar or something linke that?

### ISSUE THREAD

**Issue by narutowindy** [i3/i3status#229]
active space must be identified by whole border color, but we can use font pango markup to colorise every workspace with individual color, but at last we cannt identify which one is active workspace, so i would like to add Underline to acitve workspace with color so that i can see which one is acive in workspace.? how can i achive  that?

**Comment by Airblader** [comment]
That'd be the job of i3bar and the answer is no. This is, however, possible with the i3bar in i3-gaps, which is where polybar got the idea from anyway.
