### ISSUE TITLE
User-selectable zero/space padding on wireless fields

### ISSUE THREAD

**Issue by devkev** [i3/i3status#230]
#166/#167 changed the zero-padding on `%quality` (in wireless) to space-padding.  However, I prefer zero-padding, because with space-padding I find the extra horizontal space (between `%quality` and the entry to its left) to be distracting.  It would be nice if the user could choose between zero- and space-padding (for fields where that makes sense).

**Comment by Airblader** [comment]
This goes a bit too much into the direction of visual preferences where no side is clearly better. We're not looking to accomodate every possible scenario with i3status, so perhaps switching to another tool might be a better decision here. I'm inclined to say no to this one. @stapelberg What do you think?

**Comment by devkev** [comment]
I can say that I'm not about to switch away to another tool (after being happy with i3status for 4 years now) just because I happen to prefer `%03d` to `%3d` for a couple of fields.  That said, I am aware of the downsides of introducing these "%tag variants", as well as the downsides of allowing full customisation (eg. user-specified formats), or of not allowing any customisation at all.

**Comment by stapelberg** [comment]
Yeah, patching this locally seems viable enough (a `sed(1)` invocation might do the trick) to justify not accepting this feature.
