### ISSUE TITLE
Fixed-width %bitrate for wireless

### ISSUE THREAD

**Issue by devkev** [i3/i3status#231]
On my system the wifi bitrate often jumps between values like "585 MB/s" and "526.5 MB/s".  This is jarring because the change in width affects the alignment of all the other fields.  The cause is the way that `print_bitrate()` in `src/print_wireless_info.c` uses `%g` to print the bitrate.  However there is code in that function to choose an appropriate divisor, meaning that 3 digits (with no fractional part) should always be sufficient.  Therefore it would be more appropriate to use a format of `%3.0f` instead.

**Comment by Airblader** [comment]
Seems to be in line with similar decisions we made, so SGTM. @stapelberg Your thoughts?

**Comment by stapelberg** [comment]
SGTM
