### ISSUE TITLE
More flexible assign icons of battery status

### ISSUE THREAD

**Issue by z1trus** [i3/i3status#233]
Currently, there is possible to assign different icons of battery status. But what about adding possibility to assign different icons depending on current battery capacity? Currently it's printing in percentage, but (for example FontAwesome) has different icons like:

fa-battery-full
fa-battery-half 
fa-battery-three-quarters
fa-battery-quarter
fa-battery-empty

It'll be fine to have this possibility for graphical represent of current capacity for those, who wants to have short status bar.

**Comment by Airblader** [comment]
#161
