### ISSUE TITLE
Add FreeBSD first_eth_interface support & fix compilation

### ISSUE THREAD

**Issue by ericdahl** [i3/i3status#242]
While investigating why 2.11 did not resolve `ethernet _first_`, I found #197 which added OpenBSD support, but now results in a compilation failure on FreeBSD because there's [no implementation defined](https://github.com/i3/i3status/blob/6a19709/src/first_network_device.c#L130).

```bash
$ uname 
FreeBSD

$ gmake
src/first_network_device.c:130:2: error: Missing implementation to determine interface
      type.
#error Missing implementation to determine interface type.
 ^
1 error generated.
gmake: *** [Makefile:88: src/first_network_device.o] Error 1
```

I did not see any issue or PR tracking this.

**Comment by Airblader** [comment]
Yes, the `#error` is not good. We should've preserved the old behavior for BSDs in the case of OpenBSD.

CC @jasperla

**Comment by jasperla** [comment]
That `#error` should indeed be removed, please see #243

**Comment by eplanet** [comment]
This issue should probably be closed since it's been fixed by jasperla.

**Comment by Airblader** [comment]
Yes, thanks!
