### ISSUE TITLE
Battery status on arm64 (pinebook) not working

### ISSUE THREAD

**Issue by joekinley** [i3/i3status#244]
In the file print_battery_info.c, the battery status needs either POWER_SUPPLY_ENERGY_NOW or POWER_SUPPLY_CHARGE_NOW to fill up remaining and percentage_remaining.
But on the pinebook neither is available.
What IS available is POWER_SUPPLY_CAPACITY, and the code even is supposed to act on that in line 146, BUT as the remaining variable in the struct is initialized with 0 and not with -1, this code is never executed here.

So either the initialization should start at -1 (line 67 i assume) or, the code in 146 should check for 0, which, in my opinion should be fine, as the edge case, the battery being zero, should anyway either turn off the device, or it is powered anyways.

**Comment by Airblader** [comment]
CC @eplanet

**Comment by eplanet** [comment]
@joekinley: Thanks for reaching with the issue. Could you provide a bit more information here? What is your running version of i3status? Note that #216 has been merged in April, so no official release ship the fix yet, last being `2.11` in January.

Please also paste both your configuration file content and the content of the `uevent` file you are using, it will greatly help reproducing your issue and eventually fixing it.

**Comment by joekinley** [comment]
Sure thing. 
Here is my uevent:
`➜  ~ cat /sys/class/power_supply/battery/uevent 
POWER_SUPPLY_NAME=battery
POWER_SUPPLY_MODEL_NAME=battery
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_ONLINE=0
POWER_SUPPLY_HEALTH=Good
POWER_SUPPLY_TECHNOLOGY=LiFe
POWER_SUPPLY_VOLTAGE_MAX_DESIGN=4200000
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=3300
POWER_SUPPLY_VOLTAGE_NOW=4015000
POWER_SUPPLY_CURRENT_NOW=-1114000
POWER_SUPPLY_ENERGY_FULL_DESIGN=10204
POWER_SUPPLY_CAPACITY=96
POWER_SUPPLY_TEMP=300
`

And here is my status config:
`➜  ~ cat /etc/i3status.conf 
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 5
}

order += "ipv6"
order += "disk /"
order += "run_watch DHCP"
order += "run_watch VPN"
order += "wireless _first_"
order += "ethernet _first_"
order += "battery 0"
order += "load"
order += "tztime local"

wireless _first_ {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

ethernet _first_ {
        # if you use %speed, i3status requires root privileges
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

battery 0 {
        format = "%status %percentage %remaining %consumption"
	path = "/sys/class/power_supply/battery/uevent"
	integer_battery_capacity = true
}

run_watch DHCP {
        pidfile = "/var/run/dhclient*.pid"
}

run_watch VPN {
        pidfile = "/var/run/vpnc/pid"
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S"
}

load {
        format = "%1min"
}

disk "/" {
        format = "%avail"
}
`

**Comment by eplanet** [comment]
Great! Thanks for sharing the information so rapidly.

It appears to be working with latest `master` using your configuration and uevent file content. Here's the output: `BAT 96% 00:00:00 4.47W`. I suppose this is what you would expect to be displayed?

I don't know of any plan to release `i3status` soon, but you could build it yourself from `master` to confirm it fixes the issue.

**Comment by joekinley** [comment]
Alright, so I used the master, and tried to install it. But Apart from the packages your readme listed, I also had to install `libxml2-utils` and `xmlto` for it to work.
Then, yes it states the percentage properly now. Now just the `%remaining` is still not showing properly. But I have to take a deeper look into this I guess. 
Thanks, so I assume it is already fixed?

**Comment by eplanet** [comment]
This is very true that the README dependencies need an update. Maybe you could submit a PR since you've just done it from scratch?

It is fixed for displaying the capacity, but there might be room for improvements with fixing `%remaining` as you mentioned. Digging further in the [kernel documentation page](https://www.kernel.org/doc/Documentation/power/power_supply_class.txt) would help to implement that.

**Comment by joekinley** [comment]
I will take a deeper look into it, so we can maybe leave this open for now.
What is a PR? I could provide one if I know what it is ^^

**Comment by eplanet** [comment]
OK I'll check the doc as well so together we might be able to fix it ;-). A PR (pull request) is how we integrate contributions, check [github documentation](https://help.github.com/articles/about-pull-requests/).

**Comment by joekinley** [comment]
Oh of course... well I don't usually make those, but sure can do once I fixed stuff.

**Comment by mro** [comment]
thanks a lot, I built successfully also on a pinebook with 

```
#!/bin/sh

pkgs="libconfuse-dev \
       libyajl-dev \
       libasound2-dev \
       libpulse-dev \
       libnl-genl-3-dev \
       asciidoc \
       xmlto \
       libcap2-bin \
       libxml2-dev"

apt-mark showmanual ${pkgs} > before.manuals
sudo apt install    ${pkgs}

make -j

sudo apt-mark auto   ${pkgs}
sudo apt-mark manual $(cat before.manuals)
sudo apt autoremove
```

the `remaining`, however is 00:00:00. I think the information just isn't there.

P.S.:
```
 $  upower -i /org/freedesktop/UPower/devices/battery_battery
  native-path:          battery
  model:                battery
  power supply:         yes
  updated:              Di 26 Sep 2017 22:20:45 CEST (114 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              0 Wh
    energy-empty:        0 Wh
    energy-full:         0 Wh
    energy-full-design:  0 Wh
    energy-rate:         0 W
    voltage:             3,721 V
    percentage:          54%
    temperature:         30 degrees C
    capacity:            100%
    technology:          lithium-iron-phosphate
    icon-name:          'battery-good-symbolic'
```

**Comment by eplanet** [comment]
Should we consider that issue resolved then?

**Comment by eplanet** [comment]
@joekinley it seems that the issue is fixed, could you confirm and close it? Thanks!

**Comment by joekinley** [comment]
Yeah, this issue is resolved. Will open a new one if I get to the remaining thing
