### ISSUE TITLE
README SLOC Discrepancy

### ISSUE THREAD

**Issue by ajmeese7** [i3/i3status#248]
On the [i3 website](https://i3wm.org/i3status/) it says 'about 3000 SLOC' and in the [README here](https://github.com/i3/i3status/blob/master/README.md) it says 'about 1500 SLOC'. Which is correct?

**Comment by eplanet** [comment]
I suppose the first one...

```
$ find -name "*.[c|h]" | xargs cat | sort | uniq | wc -l
3066
```

**Comment by eplanet** [comment]
You can close that issue I suppose. Thanks!

**Comment by Airblader** [comment]
Yes. Thanks. :-)
