### ISSUE TITLE
Wireless %quality has leading zero when quality ~=100

### ISSUE THREAD

**Issue by dougmercer** [i3/i3status#25]
This is a very minor nitpick, but I'm not quite sure how to trim the leading zero from the %quality string when quality is ~=100. The reason I'm submitting this an issue and not simply assuming that it's intended behavior is because volume and battery life seem to correctly trim the zero. 

Here is an illustration of what I'm referring to http://i.imgur.com/9qhKV1P.jpg

As an aside, thank you for i3 and all of its related software. I'm just beginning to use it and am already hooked.

**Comment by stapelberg** [comment]
We’ve done this since commit 71f71660322b12b8602f5979222d280b7db333bd (June 2010) to avoid the text jumping around when your wireless quality oscillates between 100% and <100%.

You could send a pull request to introduce a new format string (format_quality) which makes this configurable.

**Comment by dougmercer** [comment]
Ah, that makes sense. I'll try to to make this a configurable setting once this semester is finished.

Thanks for the quick response!

**Comment by neiljp** [comment]
I found this problem myself, so had a play with fixing it myself.
Would you consider #115 as a fix for this?
