### ISSUE TITLE
Volume does not work with device name

### ISSUE THREAD

**Issue by reitzig** [i3/i3status#250]
This is my setup:

```bash
$ pacmd list-sinks | grep name:
	name: <alsa_output.pci-0000_01_00.1.hdmi-stereo>
	name: <alsa_output.usb-Logitech_Inc_Logitech_USB_Headset_H540_00000000-00.analog-stereo>
	name: <alsa_output.usb-FiiO_DigiHug_USB_Audio-01.iec958-stereo>

$ pacmd list-sinks | grep volume:
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	base volume: 65536 / 100% / 0,00 dB
	volume: front-left: 19650 /  30% / -31,39 dB,   front-right: 19650 /  30% / -31,39 dB
	base volume: 58409 /  89% / -3,00 dB
	volume: front-left: 6550 /  10% / -60,01 dB,   front-right: 6550 /  10% / -60,01 dB
	base volume: 65536 / 100% / 0,00 dB
```

With

```
volume music { 
        format = "♪ %volume"
        format_muted = "♪ muted (%volume)"
        device = "pulse:alsa_output.usb-FiiO_DigiHug_USB_Audio-01.iec958-stereo"
}
```

I do not get the correct volume:

![2017-12-01_01](https://user-images.githubusercontent.com/4246780/33491870-cd328888-d6bb-11e7-9bb4-91fbf103a016.png)

With `device = "pulse:3"` it works as expected (showing 10%).

Sink indices are no good in my setup; apparently they change when re-plugging devices.

FWIW, it would also be nice if i3status would be satisfied with *substrings* of sink names as long as they are uniquely identifying.

Running i3status 2.10 (that's what comes with Ubuntu 16.04).

**Comment by Watcom** [comment]
i3status 2.10 did not have that feature yet, you will have to upgrade it to 2.11 or the current github version.

**Comment by reitzig** [comment]
My bad, thanks.
