### ISSUE TITLE
Battery time remaining should not show seconds (/by default)

### ISSUE THREAD

**Issue by stevebarratt123** [i3/i3status#260]
It is unexpected that battery time remaining shows seconds. For me/most?, time in hours:min provides sufficient precision, thus the seconds are arguably just distracting and space-consuming.

As far as I can tell (looking in source and .man) there is no conf-level option to set the battery remaining time format. 

Thus, either a formatting option should exist, and/or default to hours:min.

**Comment by Stunkymonkey** [comment]
i definitely agree.
@Airblader are there reasons, why this is not default?

**Comment by Airblader** [comment]
No, I agree that second precision is useless here.

**Comment by Stunkymonkey** [comment]
:+1:  i will make an pr

**Comment by Stunkymonkey** [comment]
would you like to have the `hide_seconds` be exchanged to `show_seconds`?
but i believe this would be a breaking change

**Comment by Airblader** [comment]
No, we always want to avoid breaking changes. I'm traveling at the moment, so I didn't check whether we have an option for this already or not (as stated in the issue).

If we have am option, we can make hiding seconds the default. If we don't have one we should keep it that way but just remove the seconds.

**Comment by Stunkymonkey** [comment]
Yes `hide_seconds` already exists.
