### ISSUE TITLE
Colors from Xresources

### ISSUE THREAD

**Issue by dannycolin** [i3/i3status#263]
So I've recently modified my color scheme and for a moment I was "what the heck are my color[_good,_bad,_degrad] wrong!". And I remembered that I've set them in my i3status config and not in my Xresources like with i3. :)

So for the sake of consistency, It would be nice if i3status can fetch Xresources variables/colors like it is possible in i3 (https://i3wm.org/docs/userguide.html#xresources).

**Comment by eplanet** [comment]
Hi there! That's a good idea. I might work a bit on this if you don't plan on opening a PR.

**Comment by dannycolin** [comment]
@eplanet Hi there! That's a good idea. I might work a bit on this if you don't plan on opening a PR.

No. I didn't. My C knowledge is pretty limited :( so if you want to give it a try you are more than welcome :).

**Comment by orestisf1993** [comment]
I don't know if this is a great idea because i3status is not an X application, it works on the command line even without a X11 session and doesn't depend on xcb-util-xrm.

**Comment by dannycolin** [comment]
@orestisf1993 Any better idea (that don't involve hacky workaround like preprocessing the file) to retrieve the colors' values from i3 then?

**Comment by orestisf1993** [comment]
`xrdb -query | grep color_name | cut -f 2` but it is a bit hacky.

You could use https://github.com/tamirzb/xgetres: `xgetres i3wm.color0`

**Comment by dannycolin** [comment]
But I can't use those solutions directly in my config file. I mean i3status should in some way be able to know the colors setted by i3. After all, it's made for it.

**Comment by Airblader** [comment]
The color isn't set by i3, it's set in the X resources. And there's no good reason for i3status to access i3 directly — yes, it is typically used with i3, but it's a standalone project nonetheless.

A proper way would be to write a simple client that queries the X resources. Using xcb-util-xrm (self advertising :)) that's trivial to do.

**Comment by orestisf1993** [comment]
Closing for the reasons above. AFAICT integration with i3 can be achieved with an `exec` line in the i3 config which calls a simple client like those mentioned above, takes the variables as input and modifies the i3status config file accordingly.
