### ISSUE TITLE
PulseAudio: support muted volume

### ISSUE THREAD

**Issue by monstermunchkin** [i3/i3status#27]
The PulseAudio code in `print_volume` lacks support for muted volume. Also, would it be possible to add the device `alsa` which completely ignores PulseAudio? I'd gladly write a patch for the latter.

**Comment by Watcom** [comment]
I was going to say you can force ALSA by specifying a valid ALSA device name, but then I realized the device name is `pulse` when using PulseAudio through ALSA emulation. So I propose having the device `alsa` to mean actually the "pulse" ALSA device (#29).

As for the mute volume support, it was indeed missing. Implementation here #28.

**Comment by stapelberg** [comment]
@monstermunchkin Can you comment on pull request #29 please? We’re not clear on what the use-case is.
