### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by domenkozar** [i3/i3status#271]
Could we get i3status released? Thanks!

**Comment by Airblader** [comment]
CC @stapelberg

Makes sense, it's been a while. We should probably go through open PRs first, for potential bugfixes worth including.

**Comment by stapelberg** [comment]
Agreed. Let me know once you had a look at any open issues/pull requests and I’ll be happy to do the actual release. Thanks!

**Comment by Airblader** [comment]
@stapelberg I made a few merges and went through all the issues, tagging them. Fine with me now.

**Comment by winks** [comment]
@Airblader would it be possible to have a look at #273 as well?

The fix is trivial, so I wouldn't mind anyone rewriting it properly and discarding my PR.

**Comment by stapelberg** [comment]
Okay, all the issues seem to be sorted out, so let me get started on preparing a new release :)

**Comment by domenkozar** [comment]
Thank you!

**Comment by stapelberg** [comment]
Now done!
