### ISSUE TITLE
Why using cat to read the file content ?

### ISSUE THREAD

**Issue by su8** [i3/i3status#276]
You could use slurp mode instead `cat` 

https://github.com/i3/i3status/blob/199a6a27136a5ddb3d813185f0f8cf9185072f08/travis/run-tests.pl#L22

Can be replaced with:

```perl
        open($fh, '<:encoding(iso-8859-1)', "@_/expected_output.txt")
          or die "Could not open file '@_/expected_output.txt' $!";
        local $/ = undef; # <--- slurp mode
        $refres = <$fh>;
        close($fh);
```

---

Updated the encoding as it failed with UTF-8, it took me awhile to find out which encoding contains the degree symbol.

**Comment by su8** [comment]
You could drop the encoding as it encodes the ansi escapes the temperature symbols and returs different string that the wanted one.

**Comment by stapelberg** [comment]
Could you send a pull request for this please? Also, we shouldn’t need to use iso-8859-1 anywhere. If our tests don’t use UTF-8, that’s another bug to fix right there :)
