### ISSUE TITLE
Cannot print percentage sign

### ISSUE THREAD

**Issue by endless-love** [i3/i3status#278]
I've tried: `%`, `%%`, `\%` in the format but none of them seems to work.

I'm using i3status 2.11 (2017-01-21)

**Comment by Airblader** [comment]
Reading the code I think the issue is that we don't handle standalone % signs, effectively ignoring them. We need to make sure to go through all codepaths that replace placeholders and fix it.

Note that in libi3 we have a format_placeholders. It might make sense to think about reusing this.

**Comment by Stunkymonkey** [comment]
i will provide a fix this weekend.
