### ISSUE TITLE
Shown IP address belongs to the wrong network interface.

### ISSUE THREAD

**Issue by duskCoder** [i3/i3status#283]
Hi gents,

The following pull request added a way to show the IP address of a network interface when a label is associated to the IP: https://github.com/i3/i3status/pull/213

To achieve this, if we have a network interface named **eth0**, instead of looking for an interface which name is exactly **eth0**, we look for a network interface which name _begins with_ **eth0**.

This change leads to a problem in a setup with two different network interfaces that have the same prefix:

Example of non-working setup:
```iproute2
8: foobar: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 10.10.10.1/24 scope global foobar
       valid_lft forever preferred_lft forever
9: foo: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 20.20.20.1/24 scope global foo
       valid_lft forever preferred_lft forever
```

With the following configuration file, meant to display the IP address of the network interface named **foo**:
```libconfuse
order += "ethernet foo"

ethernet foo {
    format_up = "%ip"
}
```

Here's what I obtain:
```sh
$ i3status -c /tmp/i3status.conf | head -n 1
10.10.10.1
```
But this IP address belongs to the interface named **foobar**.

**EDIT**: I should add that the problem occurs only if **foobar** has a network interface ID lesser than  **foo**. In the above example, foobar has the ID 8 and foo the ID 9.

Thank you by advance,
Olivier

**Comment by Airblader** [comment]
Yeah, that sounds very possible. PRs to fix this welcome :-)

**Comment by duskCoder** [comment]
Hi @Airblader ,

Thank you for your answer.

I can think of two different solutions.
- follow what was recommended by the author of the original pull request, @dlrobertson and support the following format:
```libconfuse
ethernet test0:dummyiface {
    [...]
}
```
This change might be cleaner but would make the patched version possibly incompatible with a configuration from version 2.12.
- keep the current format for the configuration and look for network interfaces that either match the entire name or _begin with_ the name and are followed by a `:` sign.
example, if the interface name is `foo`.
  * `foo` would match
  * `foo:bar` would match
  * `foobar` would **not** match

What are your thoughts ?
Olivier

**Comment by dlrobertson** [comment]
@duskCoder I think allowing `<iface>:<label>` would be best I think, but I agree that it could be incompatible with prior versions.

> keep the current format for the configuration and look for network interfaces that either match the entire name or begin with the name and are followed by a : sign.
example, if the interface name is foo. 

The original PR added a `compare_to_colon` much like this. It was super easy to implement worked fine.

**Comment by duskCoder** [comment]
Hi @dlrobertson,

Thank you for your input on this!

I've started to look at what it would take to support the `<iface>:<label>` format. Here is my impression:
- it would be straightforward to determine the IP address (i.e. `%ip` specifier) because we would simply use a strict comparison against the value in `ifa_name`.
- when it comes to all other format specifiers (i.e. `%speed` for the `ethernet` section but also 
`%quality`, `%essid` and `%bitrate` which are specific to the `wireless` section):
```libconfuse
ethernet <iface> {
    format_up = "E: %ip (%speed)"
}
wireless <iface> {
     format_up = "W: (%quality at %essid, %bitrate) %ip"
}
```
then, it becomes very cumbersome to drag the full `<iface>:<label>` string everywhere
With this in mind, it seems quite overkill to me to make the `:<label>` part of the identifier because it is only beneficial to have it for the `%ip` specifier.

Also, I would like to know if you still have the original patch that you mention (i.e. with the `compare_to_colon` function). I was thinking of using a combination of `strncat()` with `strncmp()` but I'm curious to know if you had something smarter with regards to the implementation.

Kind regards,
Olivier

**Comment by Airblader** [comment]
My immediate thought was that the other solution sounds better. But I don't know too much about networking. If someone could spare a couple minutes to explain why the first solution sounds better to both of you, that'd be much appreciated.

**Comment by duskCoder** [comment]
Hi @Airblader, sorry for the delayed answer.

I described in my last comment the pro/cons (in my opinion) of using something like:
```libconfuse
ethernet <iface>:<label> {
```
and it turned out that IMO, it is not the right way forward. So I second you when you say the other solution sounds better.

I will start implementing it.

**Comment by dlrobertson** [comment]
> Also, I would like to know if you still have the original patch that you mention (i.e. with the compare_to_colon function). I was thinking of using a combination of strncat() with strncmp() but I'm curious to know if you had something smarter with regards to the implementation.

Unfortunately I do not.
