### ISSUE TITLE
inconsistent battery information showing

### ISSUE THREAD

**Issue by nolash** [i3/i3status#288]
My battery is not showing the values I expect. From the "path" parameter in battery 0:

```$ cat /sys/class/power_supply/BAT0/uevent 
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Charging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=12796000
POWER_SUPPLY_CURRENT_NOW=2977000
POWER_SUPPLY_CHARGE_FULL_DESIGN=5600000
POWER_SUPPLY_CHARGE_FULL=1802000
POWER_SUPPLY_CHARGE_NOW=501000
POWER_SUPPLY_CAPACITY=27
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=42T4865
POWER_SUPPLY_MANUFACTURER=LGC
POWER_SUPPLY_SERIAL_NUMBER=10153
```

Charge now / charge full = 501000 / 1802000 = 0.278, but `i3status` is showing 9.7%. Also, charging stops at "UNK 37%" even though the `.../uevent` numbers show > 90%.

Is `i3status` actually using this data, or other sources (aswell)?

**Comment by Airblader** [comment]
Thanks for reporting back, I'll close this then :) 

We just read it from the sysfs. I'm not sure how the kernel reads it, but AFAIK it only reads directly measurable information from the battery, so I assume this happens in the firmware.
