### ISSUE TITLE
cpu_usage prints '%0' instead of '%' for cpu 10 and only cpu 10

### ISSUE THREAD

**Issue by wmarvel** [i3/i3status#300]
cpu_usage {
     format = "%cpu10"
}

Results in printing an extra 0 after the percent sign -> '01%0' instead of '01%'. This only occurs for CPU 10, all others print correctly.

Changing the test at line 167 of print_cpu_usage.c to 'while (step <= number) {' appears to fix this issue.

**Comment by wmarvel** [comment]
i3status -v outputs (after I cloned and built to make sure it wasn't an already fixed issue):
i3status 2.12-48-g639a67f (2018-07-16) © 2008 Michael Stapelberg and contributors

**Comment by eplanet** [comment]
Good catch, thanks for the PR #301. I'll review it tonight hopefully.
