### ISSUE TITLE
Home timezone clock (feature request)

### ISSUE THREAD

**Issue by ArcturusB** [i3/i3status#303]
When moving to a different timezone, it’s convenient to have a clock of the home timezone that displays automatically. (Eg. the android deskclock does this.) Currently, this can only be done by manually by commenting and uncommenting a tztime module. 

This could be implemented by adding a boolean switch to the tztime module options. If the switch is on, only display the module when the locale timezone is different from the module’s timezone. 

I can submit a PR if you like this idea. :)

**Comment by Airblader** [comment]
Hi,

thanks for raising this feature request. I do think this is simple & useful enough to include in i3status. Feel free to send a PR!

**Comment by eplanet** [comment]
The related PR has been merged. That issue can be closed.

**Comment by ArcturusB** [comment]
Many thanks for working on this @eplanet! I’m closing the issue.
