### ISSUE TITLE
Unknown battery status "Not charging"

### ISSUE THREAD

**Issue by David96** [i3/i3status#304]
Today I suddenly got a status_unk for my battery while my battery was full and the power supply still connected.
Looking at /sys/class/power_supply/BAT0/uevent there was a »POWER_SUPPLY_STATUS=Not charging«
That doesn't seem to be expected by i3status.
Now I'm not sure whether this status only happens when the battery is full or can happen at any time - but I guess it'd be best to handle it like POWER_SUPPLY_STATUS=Discharging?
The relevant source code seems to be line 182 in print_battery_info.c
If you think so, too, I'm happy to create a pull request just adding a »|| BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Not charging")« to that line.

I'm using a Lenovo ThinkPad E540.
From BAT0/uevent:
```
POWER_SUPPLY_MODEL_NAME=LNV-45N1
POWER_SUPPLY_MANUFACTURER=LGC
POWER_SUPPLY_SERIAL_NUMBER=27831
```

**Comment by eplanet** [comment]
Thanks for reporting the issue! It's very hard to get official information for the values of that `POWER_SUPPLY_STATUS` field. After [googling](https://www.google.fr/search?q=%22POWER_SUPPLY_STATUS%3DNot+charging%22) your value, it seems you're far from alone. My guts is that you should open a PR to add support for that value (including a test case).

**Comment by leonixyz** [comment]
I think this fix was wrong, I have the exact same situation on my Framework laptop:

Battery is full, and AC connected:

    POWER_SUPPLY_STATUS=Not charging
    POWER_SUPPLY_CHARGE_FULL=3535000
    POWER_SUPPLY_CHARGE_NOW=3535000

The current status of i3status, however, shows the battery as "discharging".

IMHO the part that was added has to be moved one "else if" above:

```
diff --git a/src/print_battery_info.c b/src/print_battery_info.c
index fad8bab..1ed5cd2 100644
--- a/src/print_battery_info.c
+++ b/src/print_battery_info.c
@@ -185,9 +185,9 @@ static bool slurp_battery_info(battery_info_ctx_t *ctx, struct battery_info *bat
             batt_info->present_rate = abs(atoi(walk + 1));
         else if (BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Charging"))
             batt_info->status = CS_CHARGING;
-        else if (BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Full"))
+        else if (BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Full") || BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Not charging"))
             batt_info->status = CS_FULL;
-        else if (BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Discharging") || BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Not charging"))
+        else if (BEGINS_WITH(last, "POWER_SUPPLY_STATUS=Discharging"))
             batt_info->status = CS_DISCHARGING;
         else if (BEGINS_WITH(last, "POWER_SUPPLY_STATUS="))
             batt_info->status = CS_UNKNOWN;
```

I will be open a new PR
