### ISSUE TITLE
Volume - understand 0% Volume as Mute

### ISSUE THREAD

**Issue by abacao** [i3/i3status#306]
Hi,
Please forgive me if my issue is from being a noob but here it goes.

I have several sound outputs and I have it configured like this:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/mEt67z/i3status.png" alt="i3status" border="0"></a>

order += "volume master"
order += "volume laptop"
order += "volume hphones"
order += "volume hdmi"

volume master {
	format = "♪: %volume"
	format_muted = "♪: muted (%volume)"
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}

volume laptop {
        device = "pulse"
        format = "<span color='#00FF00'> </span>%volume"
        format_muted = "<span color='#FF0000'> </span>%volume"
        device = "pulse:alsa_output.pci-0000_00_1f.3.analog-stereo"
}

volume hphones {
        device = "pulse"
        format = "<span color='#00FF00'> </span>%volume"
        format_muted = "<span color='#FF0000'> </span>%volume"
        device = "pulse:alsa_output.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo"
}

volume hdmi {
        device = "pulse"
        format = "<span color='#00FF00'> </span>%volume"
        format_muted = "<span color='#FF0000'> </span>%volume"
        device = "pulse:alsa_output.pci-0000_00_1f.3.hdmi-stereo-extra1"
}

Is it possible to add "0% volume" considered as mute? 
My keyboard don't have a specific mute button and this way I could remove the %volume and leave only the 1st percentage and a green oe red symbol.

**Comment by Airblader** [comment]
I understand your case, but I'm leaning towards not doing this. If the entire toolchain agrees that 0% and muted are different states, I don't think i3status is the right tool in the chain to overthrow this decision due to [hardware limitation](https://xkcd.com/1172/). We might have users who would prefer muted to be displayed differently from 0% as well. I think this issue should be tackled at a different spot in your tool chain. Thanks for understanding!

**Comment by orestisf1993** [comment]
Displaying 0% as muted could be annoying as well: a user might try to unmute instead of increasing the volume but i3status would still display "muted".

**Comment by abacao** [comment]
I totally understand. I was not expecting a radical change. If this could be an option, in general, it would be great, otherwise, its fine.
example:
general {
  0volume_as_mute = true
}
This would be my goal (faked):
<a href="https://imgbb.com/"><img src="https://image.ibb.co/eX2SVK/i3status_v2.png" alt="i3status_v2" border="0"></a>

**Comment by Airblader** [comment]
> Displaying 0% as muted could be annoying as well: a user might try to unmute instead of increasing the volume but i3status would still display "muted".

Yeah, actually I think this is a pretty big reason that speaks against this change.

> If this could be an option, in general, it would be great, otherwise, its fine.

We try to stay away from too much configurability in i3status (and to some extent in i3). The cost-benefit calculation is admittedly subjective, but I think in this case the combination of what @orestisf1993 pointed out and my earlier point that I think i3status is the wrong tool to make this logical conversion outweighs the benefit here in my opinion. Thanks for understanding!

**Comment by abacao** [comment]
Besides not "going my way", I congratulate you by standing you ground and for the quick replies.
Any suggestions on how to do what I want?

**Comment by orestisf1993** [comment]
I assume that this was reopened accidentally?

> Any suggestions on how to do what I want?

How do you set the volume at 0%? Is it through a command?
