### ISSUE TITLE
Volume Module : Limit to 100%

### ISSUE THREAD

**Issue by droslean** [i3/i3status#307]
Is there any way to configure a percentage limit to the volume?

**Comment by droslean** [comment]
As I see in the code, it just reads the value from the device. So it's not possible. It has to be handled from the device and not from the i3status bar. 

Do we still need to check it somehow?

**Comment by Airblader** [comment]
i3status only displays information, it doesn't allow controlling these devices. If you want to limit your volume to a max amount, you'll have to do this on a different level as you already pointed out. :-)
