### ISSUE TITLE
CPU Usage Fails when CPU Numbers aren't Consecutive

### ISSUE THREAD

**Issue by TwentyFourD** [i3/i3status#308]
I have a Gemini running Debian which disables CPUs to save battery. When the CPUs are enabled they aren't necessarily re-enabled in order so /proc/stat might look like:

cpu ...
cpu0 ...
cpu4 ...
cpu5 ...
...

print_cpu_usage expects the cpu lines to be contain consecutively numbered cpus so it doesn't work on the Gemini. I am currently running a work around which requires you to specify the max number of CPUs in the config so isn't great (but works okay).

**Comment by TwentyFourD** [comment]
This is my current attempt to fix. Seems to work well on the Gemini but I don't have a wide enough range of systems to really test it properly on. It does two things. It uses the number of configured CPUs instead of the number of active CPUs and also adds %active to the keywords so that you can see how many processors are currently activated.
[print_cpu_usage.c.zip](https://github.com/i3/i3status/files/2407938/print_cpu_usage.c.zip)

**Comment by orestisf1993** [comment]
If you want this to be properly reviewed and merged you'll have to fork i3status, commit your changes there and make a pull request

**Comment by TwentyFourD** [comment]
I no git expert but would the first steps be something like

git checkout -b "NonConsecutiveCPUs"

Then push the branch and the changes, and then use github to make the pull request?

**Comment by orestisf1993** [comment]
Yes. A (complete) simple workflow would be to:

1. Press the fork button
2. `git clone 'https://github.com/TwentyFourD/i3status'`
3. `git checkout -b NonConsecutiveCPUs`
4. `git add -p` (to review your changes as you add them, making sure you don't commit irrelevant changes) or simply `git add src/print_cpu_usage.c`
5. `git commit --verbose` and then put the commit title in the first line, leave an empty line and then write the commit body in the next line (can simply be "Fixes #308")
6. `git push`
7. Press the pull request button from your repo or the i3status repo

**Comment by TwentyFourD** [comment]
Thanks for the help - VERY much appreciated. Hopefully I've done it right.
