### ISSUE TITLE
Pango markup setting

### ISSUE THREAD

**Issue by ixjlyons** [i3/i3status#31]
I see that Pango markup support was [added to `i3bar`](https://github.com/i3/i3/commit/e681f34ec1af4b19f9dfd9c0e8d9c29beaf3e2db) and quickly [made non-default](https://github.com/i3/i3/commit/beaf90494300640e3f811b3b99bb84296cd716e7). When it was default, it was possible to use markup in the `i3status` config -- for example:

````
disk "/" {
    format = "<span size='large' color='#ffffff'>disk:</span> %avail
}
```

I'm wondering if there would be any interest in adding a `markup` option to `i3status` general config. This would allow users who know about the markup (and consequently know of the need to escape ampersands, angle brackets, etc.) to use it, but those who don't care about additional formatting would be unaffected.

I realize, however, that features which are achievable some way other than changing the `i3status` source are generally not added, and this falls into that category. I wrote a simple wrapper script to inject `"markup": "pango"` into the JSON before passing it along to `i3bar`, and it seems to work fine. I also took my first look at the source and hacked together a solution there. It was fairly straightforward to add, so I wanted to see what others thought about it.

**Comment by stapelberg** [comment]
I think in general it’d be okay to have a `markup` option in i3status. Note that all output not directly hard-coded in i3status or supplied by the user would need to be escaped for pango markup. This might be relevant for the time module (I haven’t checked all timezones), and is definitely relevant for the wireless module which displays the ESSID.

I suppose we’d need to re-implement http://sources.debian.net/src/glib2.0/2.44.0-2/glib/gmarkup.c/?hl=2227#L2149 for that.

Unless there is something which I haven’t thought of, I think I’d merge a pull request which adds a markup option.

**Comment by ixjlyons** [comment]
Of course I hadn't thought of automatically generated content. I need to have a bit more of a look at the `i3status` source, but I'm still interested in this as a feature.

@stapelberg: how do you recommend accessing the config from 	1kj

**Comment by stapelberg** [comment]
> how do you recommend accessing the config from 1kj

What’s “1kj”? I don’t follow.

**Comment by ixjlyons** [comment]
Whoops, sorry about that. I hadn't completed my thought but the comment somehow got submitted (my cat is looking suspect:).

Anyway, here's more or less what I was going to ask:

The config options are currently not accessed in the `print_*` functions (I'm assuming by design), but I think that's where the markup escaping would happen (e.g. in the `essid` section of `print_wireless_info()`, you'd want to escape the special characters there before writing to the buffer if the markup option is enabled).

The first solution that comes to mind is to add an argument to `print_wireless_info()` indicating the Pango Markup option. I notice, however, that none of the `print_*` functions take in general config options.  This again seems to be by design, and I don't know if a relatively small feature such as this warrants breaking the pattern (that is, if there is some other way to implement it).

Stepping back a bit: should the markup option be in the general config? It *is* something that is specified in every "block" of the JSON, but if someone wanted to enable it for one module, they'd probably want it for most or all of them.

**Comment by stapelberg** [comment]
We already have functions that depend on global config options in src/output.c, I think a maybe_escape_markup() function would fit in there quite well. And yes, I think the markup option should be global.

**Comment by ixjlyons** [comment]
I've finally gotten around to working on this.

One question:
