### ISSUE TITLE
CPU usage formats incorrectly for %cpu10

### ISSUE THREAD

**Issue by Cypher1** [i3/i3status#311]
Current Behavior
<pre>
cpu_usage {
format = "%cpu10"
}
</pre>

Renders as XX%0

Expected Behavior
<pre>
cpu_usage {
format = "%cpu10"
}
</pre>

Renders as XX%

**Comment by eplanet** [comment]
Hello! Thanks for reporting the issue. Could you give us the version of `i3status` you have installed? Your issue looks like #300 (fixed by #301). Could you confirm this fixes the issue for you?

**Comment by Cypher1** [comment]
Thanks. Couldn't access the version right now but that is the same bug and
the fix makes sense.

Cheers
