### ISSUE TITLE
unable to format ddate output

### ISSUE THREAD

**Issue by ShadowPhrogg32642342** [i3/i3status#314]
trying to run i3status 2.12 with config:
```
general {
  colors = true
  interval = 5
}

order += "ddate ddtest"

ddate ddtest {
  format = "%Y-%b-%d, %{%A%N, %H%}"
}
```
results in ``/tmp/bar-ddtest.conf:8: missing opening brace for section 'ddate'``
works without the ddate {} block, using default format

**Comment by eplanet** [comment]
Why do you want to name that entry `ddtest`, you have several different configurations for `ddate`? It works if you remove it, so maybe that's sufficient for you.

**Comment by ShadowPhrogg32642342** [comment]
Yup, it works without config name, sufficient for me.

**Comment by eplanet** [comment]
OK cool! Thanks for reporting the issue.

**Comment by eplanet** [comment]
If you consider it done, would you mind closing the issue?
