### ISSUE TITLE
MINOR: Syntax error? (i3status, load)

### ISSUE THREAD

**Issue by Kreyren** [i3/i3status#323]
## I'm submitting a…

<pre>
[X] Bug
[ ] Feature Request
[X] Documentation Request
[ ] Other (Please describe in detail)
</pre>

In https://i3wm.org/i3status/manpage.html under Configuration there is mensioned:

```
load {
    format = "[ load: %1min, %5min, %15min ]"
}
```

Which results in `Error: status_command process exited unexpectedly (exit1)`

Seems to work with:

```
load {
        format = "%1min, %5min, %15min"
}
```

Relevant:
https://github.com/i3/i3/issues/3552

*Removed the rest since it seem irelevant*

**Comment by eplanet** [comment]
Hello and thanks for reporting the issue. Could you provide what `i3status` version you are running? I don't reproduce your issue with latest `master` so I suppose it's been fixed.

**Comment by eplanet** [comment]
Still, using tag or released package`2.12`, I don't get the error.

**Comment by Kreyren** [comment]
@eplanet Just to clarify..

# Steps to reproduce:
1. `cp /etc/i3status.conf /home/$USER/.config/i3status/<anyname>`
2. Open `/home/$USER/.config/i3status/<anyname>` with your preffered text editor and replace `load` function with:
```
load {
    format = "[ load: %1min, %5min, %15min ]"
}
```
3. Edit your `/home/$USER/.config/i3/config` on `bar` function for i3status to accept new config alike:
```
bar {
	position top
        status_command i3status -c /home/$USER/.config/i3status/<anyname>
    }
4. Refresh your i3 you should encounter error with i3status.

**Comment by ixjlyons** [comment]
@Kreyren it might help if you could paste the exact contents of the entire i3status config file that reproduces the issue. Also, what is the output if you run the status command in a terminal?

```
i3status -c ~/.config/i3status/config
```

**Comment by Kreyren** [comment]
CLOSED: INVALID

Noticed: 

```
general {
        colors = true
        interval = 
        color_good = "#fff600"
        color_degraded = "#999301"
        color_bad = "#302e00"
}```

Where `interval` value is missing it's variable which result in this issue based on CLI output.

My fault I'm sorry :X

**Comment by Airblader** [comment]
I'm confused as to what the situation now is. Does the issue exist with the interval set or no? Does it reproducibly exist if the interval isn't set? Because I still think it's weird that the brackets in the format string make a difference as you stated in your original post, assuming the issue lies with the interval.

So if the issue still exists, please boil down the config to a minimal setup that reproduces the issue and then post that here. Thank you!

**Comment by Kreyren** [comment]
> I'm confused as to what the situation now is. Does the issue exist with the interval set or no? Does it reproducibly exist if the interval isn't set? Because I still think it's weird that the brackets in the format string make a difference as you stated in your original post, assuming the issue lies with the interval.
> 
> So if the issue still exists, please boil down the config to a minimal setup that reproduces the issue and then post that here. Thank you!

No, the issue is invalid since i didn't have variable for the `interval` function which result in this error. 

But it confuses me since the i3status was rendering without that variable for `interval`, but i'm unable to reproduce it. :thinking: 

Recommends closing the issue.

**Comment by Airblader** [comment]
Alright, let's do that then. Thanks!
