### ISSUE TITLE
i3status prints additional formats

### ISSUE THREAD

**Issue by croemheld** [i3/i3status#337]
I don't know how to properly name this issue, so bear with me.

I used a custom i3status.conf file (listed below) and changed the i3 config file appropiately. The following settings are stored in my i3status.conf:

```
general {
        output_format = "dzen2"
        colors = true
        interval = 5
}

# order += "ipv6"
order += "disk /"
# order += "run_watch DHCP"
# order += "run_watch VPNC"
# order += "path_exists VPN"
order += "wireless wlan0"
order += "ethernet eth0"
order += "battery 0"
order += "cpu_temperature 0"
order += "load"
order += "tztime local"

wireless wlan0 {
        format_up = "%quality  %essid %ip"
        format_down = ""
}

ethernet eth0 {
        # if you use %speed, i3status requires the cap_net_admin capability
        format_up = "%ip (%speed)"
        format_down = ""
}

battery 0 {
        format = "%status %percentage %remaining %emptytime"
        format_down = "No battery"
        status_chr = " "
        status_bat = " "
        status_unk = " "
        status_full = " "
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 10
}

# run_watch DHCP {
#         pidfile = "/var/run/dhclient*.pid"
# }
# 
# run_watch VPNC {
#         # file containing the PID of a vpnc process
#         pidfile = "/var/run/vpnc/pid"
# }
# 
# path_exists VPN {
#         # path exists when a VPN tunnel launched by nmcli/nm-applet is active
#         path = "/proc/sys/net/ipv4/conf/tun0"
# }

tztime local {
        format = "%V  %A %e.%B  %H:%M:%S"
}

load {
        format = " %5min"
}

cpu_temperature 0 {
        format = " %degrees°C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input"
}

disk "/" {
        format = " %avail"
        prefix_type = custom
        low_threshold = 20
        threshold_type = percentage_avail
}
```

The i3 configuration file now contains the modified entry:

```
bar {
        status_command i3status -c /home/croemheld/.config/i3status/i3status.conf
        position top
}
```

However, when refreshing the i3bar, the output is quite confusing:

` 7.1 GB^fg(#333333)^p(5;-2)^ro(2)^p()^p(5)^fg()^fg(#FF0000)^fg(#333333)^p(5;-2)^ro(2)^p()^p(5)^fg()^fg(#FF0000)^fg(#333333)^p(5;-2)^ro(2)^p()^p(5)^fg()  81.96%^fg(#333333)^p(5;-2)^ro(2)^p()^p(5)^fg()^fg(#FF0000) 83°C^fg(#333333)^p(5;-2)^ro(2)^p()^p(5)^fg() 1.58^fg(#333333)^p(5;-2)^ro(2)^p()^p(5)^fg()06  Friday  8.February  20:18:15
`

As you probably can see, at some places the correct format is being printed (disk at the beginning, date at the end and some stuff in the middle). The only thing that bugs me are the additional characters which seem to originate from some color and position settings. How do I fix this?

**Comment by Airblader** [comment]
Remove

    output_format = "dzen2"

You're using i3bar, not dzen2.

**Comment by croemheld** [comment]
@Airblader Thanks, that was the reason.

**Comment by Airblader** [comment]
No problem!
