### ISSUE TITLE
Fails to build on arch: man: invalid option -- 'o'

### ISSUE THREAD

**Issue by orestisf1993** [i3/i3status#338]
After https://github.com/i3/i3status/pull/316:

```
  CC       src/i3status-pulse.o
  GEN      man/i3status.xml
  CCLD     i3status
  GEN      man/i3status.1
man: invalid option -- 'o'
Try 'man --help' or 'man --usage' for more information.
make[1]: *** [Makefile:1952: man/i3status.1] Error 1
make[1]: Leaving directory '/home/orestis/.cache/yay/i3status-git/src/i3status/build'
make: *** [Makefile:686: all] Error 2
```

Also see latest comment in https://aur.archlinux.org/packages/i3status-git/

**Comment by stapelberg** [comment]
Can you build with V=1 please?

Probably something is going wrong in these lines: https://github.com/i3/i3status/blob/49461ac56f3cbea432f4c6ec547410162237fcf7/Makefile.am#L14-L16

**Comment by stapelberg** [comment]
My first guess would be that xmlto is missing.

**Comment by orestisf1993** [comment]
Indeed. We could conditionally build the man pages like in https://github.com/i3/i3/blob/e2d6117b8c2cef91c5209eac3e5b0721b3522eb0/configure.ac#L128-L133

@Airblader can you add xmlto to i3status-git's makedepends. It is also missing from i3-git.

Closing since this is not a bug.

**Comment by stapelberg** [comment]
I do wonder why you didn’t get a proper error message, though. Could you provide the full build log please?

**Comment by orestisf1993** [comment]
[out.txt](https://github.com/i3/i3status/files/2849404/out.txt)

**Comment by Airblader** [comment]
@orestisf1993 

> @Airblader can you add xmlto to i3status-git's makedepends. It is also missing from i3-git.

Done for both i3status-git and i3-git.
