### ISSUE TITLE
Insufficient capabilities to check for VPN status

### ISSUE THREAD

**Issue by snake-scaly** [i3/i3status#342]
The only way to check for VPN status with NetworkManager currently seems to be the Path-exists module. Documentation suggests to check for existence of /proc/sys/net/ipv4/conf/tun0. In my case it's /proc/sys/net/ipv4/conf/vpn0 with OpenConnect. Unfortunately this directory stays there even after the connection breaks. This includes disconnecting VPN with `nmcli con down`.

I know of two ways to check if the VPN connection is actually up:

1. Check if /sys/class/net/vpn0/operstate contains "up". After disconnecting it still exists but contains "down".
2. Check if `nmcli con show --active | grep -i vpn` output is non-empty.

It would be nice if one of these ways was supported, e.g. check if file contents match a string.

i3status 2.11 (2017-01-21)
i3 version 4.14.1 (2017-09-24)
Linux Mint 19 Tara Cinnamon

**Comment by thrasymache** [comment]
In the development version, but not in the most recent release, there is a file_contents/read_file module. You can 
  1. use that to add the contents of /sys/class/net/vpn0/operstate to your status line.
  2. make a little shell script daemon to store the results of `nmcli con show --active | grep -i vpn` in a file and add the contents of that file to your status line

**Comment by snake-scaly** [comment]
Thank you, I tried the development version and it worked perfectly. Here's the order I used:

```
read_file VPN {
    path = /sys/class/net/vpn0/operstate
    format = "%title %content"
    format_bad = "%title down"
    max_characters = 8
}
```

**Comment by thrasymache** [comment]
Watch out for the max_characters - it crashed on me if it was ever less than the length of the file. I just put in a pull request to fix that issue.
