### ISSUE TITLE
[Feature Request] Hide When Not Found or Available

### ISSUE THREAD

**Issue by zero77** [i3/i3status#346]
Can you add the option to hide entries from i3status when things are not found when using run_watch or path_exists also, when there's no wireless or ethernet connected.
Thanks

**Comment by Airblader** [comment]
i3bar will not print blocks which have an empty output, so for commands like path_exists you can use format_down="" to produce empty output which then hides the block. This is also documented in the man page:

>    Path-exists
       Checks if the given path exists in the filesystem. You can use this to
       check if something is active, like for example a VPN tunnel managed by
       NetworkManager. There also is an option "format_down". You can hide the
       output with format_down="".

**Comment by zero77** [comment]
@Airblader 
Thanks, i did not realise that using format_down would work.
