### ISSUE TITLE
Tag a 2.13 release?

### ISSUE THREAD

**Issue by Denton-L** [i3/i3status#348]
Hello, this isn't a high priority issue but it would be nice if a 2.13 release could be tagged. It's been over a year since 2.12 was released (May 11, 2018) so it would be nice to have a new version with all of the commits since then. (In particular, I'm waiting for #325).

Thanks!

**Comment by Airblader** [comment]
@stapelberg

**Comment by stapelberg** [comment]
Thanks for the reminder. I’ll get started on release preparations.

**Comment by stapelberg** [comment]
done with commit f791b4af3fd250c193c9a165e02305d138222c98
