### ISSUE TITLE
Build fails without pulseaudio

### ISSUE THREAD

**Issue by jasperla** [i3/i3status#352]
On OpenBSD we don't use pulseaudio to get volume, however `src/pulse.c` is compiled in but [configure never checked for Pulseaudio on !Linux](https://github.com/i3/i3status/blob/master/configure.ac#L87) so the required libraries aren't added to LDFLAGS. This eventually results in undefined references to various pulseaudio functions.

Would it be possible to have a define in `config.h.in` to use as a guard in `src/pulse.c` or otherwise make compiling said file conditional based on the presence of Pulseaudio?

**Comment by Airblader** [comment]
I'm in principal OK with this, we already do compilation based on the system in i3status anyway. CC @stapelberg

**Comment by stapelberg** [comment]
Not compiling pulse.c on non-linux OS sounds like a reasonable solution for this. Could you send a PR please?

**Comment by stapelberg** [comment]
@sur5r informs me that the build fails on Debian with kFreeBSD and hurd.

I think we should move the PKG_CHECK_MODULES out of the conditional in configure.ac.

**Comment by stapelberg** [comment]
@jasperla Can you confirm whether my commit 1999d5cf555c6f373549840d40f8565dcabad93b fixes the issue for you?
