### ISSUE TITLE
2.12: NetBSD patch

### ISSUE THREAD

**Issue by 0-wiz-0** [i3/i3status#358]
(Still applies to 2.13)

For the AF_INET and AF_INET6 symbols, on NetBSD you need to include `<sys/socket.h>`.

--- src/print_wireless_info.c.orig      2019-01-23 08:03:56.000000000 +0000
+++ src/print_wireless_info.c
@@ -61,6 +61,7 @@
 
 #ifdef __NetBSD__
 #include <sys/types.h>
+#include <sys/socket.h>
 #include <net80211/ieee80211.h>
 #define IW_ESSID_MAX_SIZE IEEE80211_NWID_LEN
 #endif

**Comment by Airblader** [comment]
Thanks for bringing this up. Would you like to send a PR for this?

**Comment by 0-wiz-0** [comment]
Sure! I just created one.
