### ISSUE TITLE
2.13: pulseaudio required everywhere, but only checked on Linux

### ISSUE THREAD

**Issue by 0-wiz-0** [i3/i3status#359]
`pulse.c` is used unconditionally, as is `print-volume.c`. Both contain unconditional references to pulseaudio functions.

It would be great to have this condiitonal on an autoconf test.

Right now, the configure script only looks for pulseaudio on Linux, breaking the build everywhere else.

**Comment by Piraty** [comment]
This is exactly why i opened #357

**Comment by Airblader** [comment]
@stapelberg Since you rejected the PR, could you look at this?

**Comment by stapelberg** [comment]
This should be addressed by https://github.com/i3/i3status/commit/54e798e3a6dcf5747c3e943b376ae441ee0534a4.

Which platform are you reporting this for?

**Comment by 0-wiz-0** [comment]
Thanks, (a version of) the patch in 54e798e does indeed fix the problem for me on NetBSD.

I disagree on the logic though. It's perfectly easy to install pulseaudio on OpenBSD or DragonflyBSD; and on the other hand, it's quite easy to run NetBSD without pulseaudio. That's actually the default.

This should not be a check on the operating system type, but on the existence of a pulseaudio installation, or if that is against your philosophy, then perhaps on the explicit request of the person building i3status.

**Comment by stapelberg** [comment]
> It's perfectly easy to install pulseaudio on OpenBSD or DragonflyBSD

I was given to understand that pulseaudio just doesn’t work on these platforms. If it does, we should indeed change the current logic.

> This should not be a check on the operating system type, but on the existence of a pulseaudio installation, or if that is against your philosophy, then perhaps on the explicit request of the person building i3status.

If the above is true, I would just want to link pulseaudio everywhere and not make it optional in any way.

Distributions which disagree can easily carry https://github.com/i3/i3status/commit/54e798e3a6dcf5747c3e943b376ae441ee0534a4

**Comment by 0-wiz-0** [comment]
My understanding is that pulseaudio is an audio framework that you might want to use, but don't have to. Perhaps that's different on Linux, but I think even there you have the choice of alsa.

On NetBSD, the default sound system is one coming with the operating system (which uses/provides the SunOS API); a compatibility layer exists for OSS. pulseaudio is an optional package that you might want to install for software that doesn't support any of the other ones properly, but I'm not aware of any software that really needs it.

So from my (NetBSD-based) PoV, pulseaudio support in i3status is not needed; it's a very niche user group that will benefit from it. SunOS or OSS audio support would be more useful there.

**Comment by stapelberg** [comment]
> pulseaudio is an optional package that you might want to install for software that doesn't support any of the other ones properly, but I'm not aware of any software that really needs it.

What about *users* who want it, though? Network streaming via pulseaudio seems pretty popular in my bubble, for example.

**Comment by 0-wiz-0** [comment]
Good question! I don't know in general.

In NetBSD I have the impression that people want to avoid using pulseaudio though. pkgsrc supports optional dependencies, and I've noticed quite a few times that users wanted to turn off the pulseaudio option. I get the idea it is seen as a Linux thing.

My impression (again) is it was mainly used for the mixing support, i.e. multiple concurrent audio writers. Nowadays NetBSD has an in-kernel audio mixer, so that reason is gone.

**Comment by Piraty** [comment]
Regarding @stapelberg's [post about optional dependencies](https://michael.stapelberg.ch/posts/2019-05-23-optional-dependencies/):
In this specific case (pulseaudio), (as of now) i3status *already* has an optional code path which only depends on the OS where it is compiled. So to comply with your own rules, you need to
- either enforce the usage of pulseaudio on all platforms alike
- or make it an optional path for everybody that can be enabled or disabled on distros' or users' (hey, some people build this stuff on their own behalf or use ports-like systems that provide them with build-options they can pick) choice.

You could (and should) enforce your desired set of default options and users could have to *explicitly* diverge from that set.

If this is all about keeping support overhead low, you could only provide support for that set you define as default, but i doubt many distro users will open tickets on your project's issue page before consulting their distro...
Your point about "bit rot" can be tackled by automated builds (which i see you do already with travis).

Interistingly, an [old article of yours](https://michael.stapelberg.ch/posts/2019-03-10-debian-winding-down/) came to my mind. You complained about a project refusing patches which would make the packagers life more easy. Here you do the same.

**Comment by stapelberg** [comment]
I want to address this, but I’m traveling this week. Please have a little patience.

**Comment by stapelberg** [comment]
Now fixed to conform to the best practices which the article lays out.

Please take a look and let me know if any further changes are needed before we can cut a new release.

**Comment by 0-wiz-0** [comment]
Seems to work fine for me both with pulseaudio enabled and disabled.

On NetBSD, I get a couple compilation warnings about unused code:
````
../../i3status/src/print_cpu_usage.c:48:12: warning: ‘cpu_count’ defined but not used [-Wunused-variable]
 static int cpu_count = 0;
            ^~~~~~~~~
../../i3status/src/print_mem.c:42:13: warning: ‘memory_absolute’ defined but not used [-Wunused-function]
 static long memory_absolute(const long mem_total, const char *size) {
             ^~~~~~~~~~~~~~~
../../i3status/src/print_mem.c:21:12: warning: ‘print_bytes_human’ defined but not used [-Wunused-function]
 static int print_bytes_human(char *outwalk, uint64_t bytes) {
            ^~~~~~~~~~~~~~~~~
../../i3status/src/print_mem.c:15:19: warning: ‘memoryfile_linux’ defined but not used [-Wunused-const-variable=]
 static const char memoryfile_linux[] = "/proc/meminfo";
                   ^~~~~~~~~~~~~~~~
````
and when pulseaudio is disabled, the ones above plus a couple more:
````
../../i3status/src/print_volume.c: In function ‘print_volume’:
../../i3status/src/print_volume.c:361:1: warning: label ‘out’ defined but not used [-Wunused-label]
At top level:
../../i3status/src/print_volume.c:51:14: warning: ‘apply_volume_format’ defined but not used [-Wunused-function]
 static char *apply_volume_format(const char *fmt, char *outwalk, int ivolume, const char *devicename) {
              ^~~~~~~~~~~~~~~~~~~
````

**Comment by stapelberg** [comment]
Thanks for testing! Can you send a PR to address the warnings please?

**Comment by 0-wiz-0** [comment]
I've opened https://github.com/i3/i3status/pull/361 for this.

Just now when testing I saw this once when interrupting i3status:
````
=================================================================
==463==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 34 byte(s) in 1 object(s) allocated from:
    #0 0x760ce0225f3c in realloc /usr/src/external/gpl3/gcc/dist/libsanitizer/asan/asan_malloc_linux.cc:80
    #1 0x760cdd73c15f in _vasprintf_l /usr/src/lib/libc/stdio/vasprintf.c:74
    #2 0x7f7fff84258f  (<unknown module>)

Indirect leak of 2048 byte(s) in 1 object(s) allocated from:
    #0 0x760ce0225bc8 in __interceptor_malloc /usr/src/external/gpl3/gcc/dist/libsanitizer/asan/asan_malloc_linux.cc:67
    #1 0x760cdf603d04 in yajl_buf_ensure_available /scratch/devel/yajl/work/lloyd-yajl-66cb08c/src/yajl_buf.c:42
    #2 0x760cdf603d04 in yajl_buf_append /scratch/devel/yajl/work/lloyd-yajl-66cb08c/src/yajl_buf.c:73

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x760ce0225bc8 in __interceptor_malloc /usr/src/external/gpl3/gcc/dist/libsanitizer/asan/asan_malloc_linux.cc:67
    #1 0x760cdf60466c in yajl_gen_alloc /scratch/devel/yajl/work/lloyd-yajl-66cb08c/src/yajl_gen.c:114
    #2 0x40455c in ___start (/disk/6/archive/foreign/i3status-fork/build/./i3status+0x40455c)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x760ce0225bc8 in __interceptor_malloc /usr/src/external/gpl3/gcc/dist/libsanitizer/asan/asan_malloc_linux.cc:67
    #1 0x760cdf603c23 in yajl_buf_alloc /scratch/devel/yajl/work/lloyd-yajl-66cb08c/src/yajl_buf.c:58

SUMMARY: AddressSanitizer: 2690 byte(s) leaked in 4 allocation(s).
````
It seems the interrupt-catching-exit-path is not completely cleaning up. I didn't worry much about this since it's exiting anyway, but just to let you know.
