### ISSUE TITLE
Wrong used memory value shown intermittently

### ISSUE THREAD

**Issue by eerie** [i3/i3status#365]
- i3status 2.13
- i3 4.17
- distro: archlinux32

I've set this in /etc/i3status.conf

```
memory {                                                                         
        format = "MEM: %used "                                                                                                                                 
}
```

but the used memory value in i3status bar is shown alternatively in GiB (with the correct value) and in TiB (with a value totally wrong), toggling between them randomly apparently for rather long periods of time
![2019-09-02_i3wm_screenshots_sidebyside](https://user-images.githubusercontent.com/1623676/64084135-76fa1e80-cd28-11e9-8759-0fcf2911a2cd.png)

**Comment by eplanet** [comment]
Thanks for reporting the issue. That would be very helpful if you could post your `/proc/meminfo` content in both cases. That way we could investigate easily what exactly goes wrong in [src/print_mem.c](https://github.com/i3/i3status/blob/master/src/print_mem.c). Thanks!

**Comment by eerie** [comment]
I seem to have identified the behaviour: it seems that the value is shown correctly until it is <= 2GiB, then it becomes wrong when the used memory value exceeds 2GiB.

```/proc/meminfo``` when memory usage is: 1.6 GiB and shown correctly:  http://ix.io/1Uql
```/proc/meminfo``` when memory usage is:  > 2GiB and shown wrong:  http://ix.io/1Uqa

**Comment by eplanet** [comment]
So I tested with both your files, and I get the following output for format `MEM: %free %available (%used) / %total`:
- `MEM: 1.6 GiB 1.8 GiB (1.6 GiB) / 3.8 GiB` (first `/proc/meminfo`)
- `MEM: 318.2 MiB 1.4 GiB (2.0 GiB) / 3.8 GiB` (second `/proc/meminfo`)

In other words, I seem to be incapable of reproducing your craziness bug.
