### ISSUE TITLE
Add switch to disable docs build

### ISSUE THREAD

**Issue by protonesso** [i3/i3status#377]
Hi. I'm user of i3 windows manager and looking at this project. It seems very nice extension for the window manager. I wanted to build it. I have downloaded the source, unpacked it and ran autoreconf -fi. But the ./configure requires asciidoc and xmlto. I don't want to install any documentation and I've tried to remove it on my own. But I failed. Can you add "--disable-docs" switch or stuff like that? That would be great!

**Comment by Airblader** [comment]
Why are you building from source rather than installing a package? We generally recommend people not to build from source.

**Comment by protonesso** [comment]
Because I'm not using distro with i3status binary provided?

**Comment by Airblader** [comment]
I think a better solution would be to get it packaged for your distro then. :-) These are make dependencies, so with a package you won't have to install them. Which distro are you using, by the way?

**Comment by protonesso** [comment]
My own. I don't like building and installing documentation because it wastes my disk space. I also use it on devices with smaller storage spaces.

**Comment by Airblader** [comment]
Alright, gotcha. If you want to send a PR for this I think it'd be OK.
