### ISSUE TITLE
[Request] Transparency Option

### ISSUE THREAD

**Issue by zero77** [i3/i3status#379]
Can you please add an option to set the level of transparency ranging from completely see through to not at all, thanks.

**Comment by Airblader** [comment]
This is a foot gun kind of option that I don't think we want to support, sorry

**Comment by zero77** [comment]
@Airblader 
Do you know of any way to do this at the moment.
Because, i am trying to use cmatrix as a background/screen saver on the lock screen.

**Comment by Airblader** [comment]
You can probably define transparency in your compositor for the window. Or use something like xtrlock.

**Comment by zero77** [comment]
Sorry, i just realised i posted this on the wrong repo

**Comment by Airblader** [comment]
I hadn't noticed either, my answer is for i3lock. :-)
