### ISSUE TITLE
format color on tztime does not work as documented

### ISSUE THREAD

**Issue by oriold** [i3/i3status#382]
This should work as per documentation on version 2.13, but it doesn't. The span is uninterpreted, and you can see full string instead.
```
tztime nyc {  
    format = "<span color='#ffff00'>%time</span>"
    format_time = "%H:%M NYC"
    timezone = "America/New_York"
}
```

**Comment by Airblader** [comment]
Did you set "markup" to "pango"?

**Comment by oriold** [comment]
No, apologies. That said I think the documentation doesn't make that clear that general option "markup" is available. Is working, thanks. Closing.

**Comment by Airblader** [comment]
I agree that this isn't extremely clear. I wouldn't mind a PR that references this in the appropriate places if you feel like improving it!
