### ISSUE TITLE
How could I show verr num state ?

### ISSUE THREAD

**Issue by Stargateur** [i3/i3status#383]
My laptop don't have a verr num indicator led, can I show it somehow on my i3bar ?

I didn't find anything in the documentation.

**Comment by su8** [comment]
Hi @Stargateur you can try out my small program https://github.com/su8/numcapslock-indicator

**Comment by Stargateur** [comment]
Will answer you at the end of coronavirus crisis, I don't use my work laptop. Thank you.

**Comment by orestisfl** [comment]
Let us know if it doesn't work for you
