### ISSUE TITLE
use format_placeholders in all print-modules

### ISSUE THREAD

**Issue by Stunkymonkey** [i3/i3status#384]
Just to keep track what is already implemented:
- [X] `battery_info`
- [x] `cpu_temperature`
- [ ] `cpu_usage`
- [x] `ddate`
- [x] `disk_info`
- [x] `eth_info`
- [x] `file_contents`
- [x] `ip_addr`
- [x] `ipv6_addr`
- [x] `load`
- [x] `mem`
- [x] `path_exists`
- [x] `run_watch`
- [x] `time`
- [x] `volume`
- [x] `wireless_info`

@Airblader is it wanted to use `format_placeholders` in all modules? even in `cpu_usage`?

**Comment by Airblader** [comment]
In general yes, I'd try to do this consistently. If there's a good reason not to use it in one of the modules we should evaluate them.

**Comment by Stunkymonkey** [comment]
@Airblader can you have a quick look at the `cpu_usage` code and think about how we are implementing this with format_placeholders?
What we definetly do not want to do; is allocating one giant placeholder struct; which then would have a constant size.

**Comment by Airblader** [comment]
If there's a good reason for not using the function in that module then I'm also fine leaving that one out.

**Comment by Stunkymonkey** [comment]
complexity wise i would like to leave out the `cpu_usage`.

If we would implement it, we would have to allocate one giant placeholder which contains all variables for all cores which. This means for a multi-core machine (e.g. 96cores) if would be a little memory overhead.
We would not only allocate the memory but also call the `snprintf` the same amount of times. Even if we would only use a single variable out of all of them.

**Comment by Stunkymonkey** [comment]
@Airblader can we close this issue?

**Comment by Stunkymonkey** [comment]
ping @orestisfl ?
