### ISSUE TITLE
Module to display the percentage of backlight intensity

### ISSUE THREAD

**Issue by qlem** [i3/i3status#388]
Hi,

Many people asked for adding a module that display the current percentage of backlight intensity (monitor brightness). 5 PRs were done, all rejected for obscure reasons !

Why ?!

[Link to the last PR](https://github.com/i3/i3status/pull/184)

**Comment by Airblader** [comment]
In cases like this I like referring to @stapelberg to revisit his decision given the interest in the topic and the age of the decision.

**Comment by stapelberg** [comment]
The rationale in https://github.com/i3/i3status/pull/73#issuecomment-147174223 still holds.
