### ISSUE TITLE
 the icon batery did change to a cloud randomly and i cant change it from the i3status config  file

### ISSUE THREAD

**Issue by themythtoon** [i3/i3status#406]
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)

the icon batery did change to a cloud randomly and i cant change it from the i3 bar config file 

i3 version: 

i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18 (2020-02-18) (pid 1205)o abort…)
Loaded i3 config: /home/themythtoon/.i3/config (Last modified: vie 03 abr 2020 18:19:19, 9486 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

- Linux Distribution & Version: manjaro 19.0.2

file:///root/.i3/config
file:///root/.config/i3status/config

a hpoto showing how the "cloud" looks like
https://imgur.com/zNlmI6o

**Comment by Airblader** [comment]
> file:///root/.i3/config
> file:///root/.config/i3status/config

Unless you're sending me your hard drive that doesn't help us :-)

---

i3status doesn't show icons on its own, so this is likely an issue with the icon font or your config, therefore closing the issue. If you can reproduce this with text please upload configs and log file as described. Thanks!
