### ISSUE TITLE
Build from release archive cannot determine release version

### ISSUE THREAD

**Issue by afh** [i3/i3status#41]
The Makefile uses git to determine the current release number, this does not work when building from a release archive, since the release archive does not contain the git history.

**Steps to reproduce:**
```
% curl -Ls https://github.com/i3/i3status/archive/2.9.tar.gz | tar zxvf -
% make -C i3status-2.9
fatal: Not a git repository (or any parent up to mount point /Volumes/Users)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

What other ways could be used to put the release version information into the release archive?

**Comment by Airblader** [comment]
Why do you want to build manually from a release archive? You can just check out the repository and do `git checkout 2.9`

**Comment by afh** [comment]
I want to manually build from a release archive to include i3status into the Mac OS X [Homebrew](http://brew.sh) package manager.

**Comment by Airblader** [comment]
And why can't you do it the way I mentioned above?

**Comment by afh** [comment]
I could, yet the Homebrew maintainers strongly prefer "official" release archives to be used and my pull request for the new formula would likely be rejected.

Personally I also think an official release archive should build correctly independent of an development environment.

**Comment by stapelberg** [comment]
The official releases can be found at http://i3wm.org/i3status/, not at GitHub.

**Comment by afh** [comment]
Good to know, thank you.
