### ISSUE TITLE
i3status does not allow selective pango-markup in tztime-module

### ISSUE THREAD

**Issue by cherti** [i3/i3status#421]
`i3status` only supports global pango-markup in the tztime-module via the `format_time`-helper construct. This does not allow for selective markup, for example to aid readability by distinguishing clock and date by color.

Minimal (desired) config example:
```
general {
        colors = true
        interval = 60
        markup = "pango"
}

order += "tztime local"

tztime local {
        format = "%a <span foreground='#bbbbbb'>%Y-%m-%d</span> %H:%M"
}
```

Expected result:
`Thu 2020-06-11 22:00` with slightly darker `2020-06-11`.

Actual result:
`Thu &lt;span foreground=&apos;#bbbbbb&apos;&gt;2020-06-11&lt;/span&gt; 22:00`, all in one color.

As the `format_time`-directive is a single hardcoded option, this is not capable of producing the desired markup.

CC @sur5r

**Comment by stapelberg** [comment]
Sounds good to me. I can review this.

**Comment by wwalker** [comment]
For others who are having trouble making this work (until we have a fix):

I worked around this with the following, but it is a very ugly workaround.
```
order += "tztime local1"
order += "tztime local2"
order += "tztime local3"
order += "tztime local4"

tztime local1 {
    format = "<span foreground='CadetBlue3'>%time</span>"
    format_time = "%a"
    timezone = America/Chicago
}

tztime local2 {
    format = "<span foreground='green'>%time</span>"
    format_time = "%F"
    timezone = America/Chicago
}

tztime local3 {
    format = "<span foreground='white'>%time</span>"
    format_time = "%T"
    timezone = America/Chicago
}

tztime local4 {
    format = "<span foreground='CadetBlue1'>%time</span>"
    format_time = "%Z"
    timezone = America/Chicago
}
```

**Comment by wwalker** [comment]
On a different note, is there any problem with a solution that just calls `strftime()` on any part of "format" that matches one or more valid `strftime()` conversions specifiers separated by `([[:space:]]|[-:._])*`

Worst case we call `strftime()` for every separate conversion specifier...
` *%[_-0^#][a-z]
