### ISSUE TITLE
maybe_escape_markup introduces random characters

### ISSUE THREAD

**Issue by cherti** [i3/i3status#432]
The function `maybe_escape_markup` in `src/output.c` (sometimes) introduces random characters into the processed string. So far I could observe this only with the wireless module and the essid-variable.

The behavior can be observed by introducing `printf("%s---%s\n", text, *buffer);` after https://github.com/i3/i3status/blob/master/src/output.c#L122.
One exemplary result can be seen here: https://p.nnev.de/9562

The behavior was verified on the text console, hinting at random characters, when using i3status as the status command of swaybar, this effectively destroys the formatting (besides other symptomes one can see broken utf-8-characters(?)), so it might not only be ascii characters being introduced here, although this test only indicates ascii-characters.

This issue could be reproduced on two Arch Linux installations with a hand-compiled i3status master. Interestingly, when using the packaged version of i3status, while sticking to the way the package was built, the issue did not occur there.

CC @stapelberg

**Comment by stapelberg** [comment]
My first guess would be that the buffer passed as second parameter to `maybe_escape_markup` is not `\0`-terminated.

Looking at the code, the buffer is declared but not explicitly initialized:
https://github.com/i3/i3status/blob/3451a0d9fc81c69d4dcaf93b511459b164df05e8/src/print_wireless_info.c#L557

Can you see if the problem disappears when you explicitly `memset()` these buffers to contain all-zero?

**Comment by cherti** [comment]
I'll test this. To clarify, I only observed this behavior in the `essid`-field (which doesn't mean it might not happen in others as well, of course and I don't see that the essid-code is significantly different from the others). Just noticed that I didn't mention that explicitly, for completeness of the report.

**Comment by cherti** [comment]
Yes, both `memset(string_essid, '\0', STRING_SIZE);` as well as `memset(string_essid, 0, STRING_SIZE);` seem to resolve the issue (not sure if there is a functional difference between the two, my C is to rusty for that. The second one can be found in other parts of the code, so this seems to be preferred).

If you consider this the best solution to the problem I can do that for all those fields (just to be safe) and make a PR (unless it's more convenient for you to just fix it).

**Comment by orestisfl** [comment]
We seem to be using `= {'\0'};` here:
https://github.com/i3/i3status/blob/3451a0d9fc81c69d4dcaf93b511459b164df05e8/src/print_volume.c#L94

so it would be ok to use this syntax as well

@cherti please do :)
