### ISSUE TITLE
'Error: status_command process exited unexpectedly (exit 1)' in i3bar

### ISSUE THREAD

**Issue by ioanclarke** [i3/i3status#446]
logfile: [here](https://logs.i3wm.org/logs/5639660982239232.bz2)
i3 version 4.19
i3status version 2.13

My i3bar displays 'Error: status_command process exited unexpectedly (exit 1)' in the bottom right-hand corner. I have tried every solution I found on the web but nothing has worked. Any suggestions?

**Comment by orestisfl** [comment]
1. Run `i3status` from the command line. Does it crash with an error?
2. Run `i3bar -V --bar_id=bar-0`. Also redirect the output so that you can upload it here. Wait for the error (in the bar), press ctrl-c to exit.

**Comment by ioanclarke** [comment]
> 1. Run `i3status` from the command line. Does it crash with an error?
> 2. Run `i3bar -V --bar_id=bar-0`. Also redirect the output so that you can upload it here. Wait for the error (in the bar), press ctrl-c to exit.

1. When running 'i3status', I get 'Could not set locale. Please make sure all your LC_* / LANG settings are correct'. I managed to fix this earlier by running 'export LANG=C'. After doing this fix, running 'i3status' gave me the proper output. Howerver, it appears this was not a permanent solution.
2. This makes the proper output of i3status show up in i3bar! It does not result in an error. The output from running the command is attached.
[output.txt](https://github.com/i3/i3status/files/5823162/output.txt)

**Comment by orestisfl** [comment]
Then it seems that your locale settings are wrong. I don't know the specifics of your environment but you should follow the instructions of your distribution in order to configure this correctly. For example, arch instructions will probably apply to most environments: https://wiki.archlinux.org/index.php/locale.

> 'export LANG=C'. After doing this fix, running 'i3status' gave me the proper output. However, it appears this was not a permanent solution.

Yes, exporting a variable will only work for the current shell.

Closing this since it seems that it is not an i3* issue but don't feel discouraged to respond if you have further problems.

**Comment by ioanclarke** [comment]
Thank you for the help. I am using Arch, and I followed the advice from the wiki and I couldn't resolve the  'Could not set locale. Please make sure all your LC_* / LANG settings are correct' error. The only way I managed to get it working was to put 'LC_ALL="en_US.UTF-8"' in /etc/environment. So more of a workaround than a fix, but it'll do for now.
