### ISSUE TITLE
overflow in memory computation for 32-bit userland

### ISSUE THREAD

**Issue by myier** [i3/i3status#460]
I have a system with 4GB of memory and the %available fails to compute when there is 2GB or more of available memory, instead it reports 16777216.0 TiB.

I'm using debian package 2.13-3 for armhf, userland is 32 bits, the kernel is armv8 64 bits.

Thank you

**Comment by orestisfl** [comment]
Fixed by https://github.com/i3/i3status/pull/373

@stapelberg Maybe it's time for a release? :)

**Comment by stapelberg** [comment]
> @stapelberg Maybe it's time for a release? :)

Yeah. I realized recently that all color output was broken, and have just completed a series of commits to fix that.

If you could confirm that i3status still works with your config, too, that’d be great before I push a new release, possibly this weekend.

**Comment by orestisfl** [comment]
I don't really use/have an i3status config but changes LGTM.
