### ISSUE TITLE
i3status man page vs. separator_symbol

### ISSUE THREAD

**Issue by jidanni** [i3/i3status#475]
$ man i3status says  

>      If you don’t fancy the vertical separators between modules
>        i3status/i3bar uses by default, you can employ the separator directive
>        to configure how modules are separated. You can also disable the
>        default separator altogether by setting it to the empty string. **You
>        might then define separation as part of a module’s format string. This
>        is your only option when using the i3bar output format as the separator
>        is drawn by i3bar directly otherwise.** For the other output formats, the
>        provided non-empty string will be automatically enclosed with the
>        necessary coloring bits if color support is enabled.
> 

But in fact the user can just use 
```
bar {
    separator_symbol ":|:"
}
```
in .config/i3/config .

**Comment by Airblader** [comment]
I don't understand this issue. Can you please go into more detail here on how your example contradicts the documentation?

**Comment by jidanni** [comment]
All I know is reading the i3status man page,
I proceeded to add spaces in ~/.i3status.conf,
```
ethernet _first_ {
        format_up =   "   E: up"
        format_down = "   E: down"
}

disk "/" {
        format = "   %avail"
}

load {
        format = "   %1min"
}
```
Rather silly it turns out, as all I needed to do is in
~/.config/i3/config do
```
bar {
    status_command i3status
    separator_symbol "   "
}
```

**Comment by Airblader** [comment]
OK, thanks. I don't see any issue here, the man page describes this (not that it needs to, i3status is independent of i3bar).
