### ISSUE TITLE
Feature request: Make space between workspace names configurable

### ISSUE THREAD

**Issue by bad63r** [i3/i3status#508]
Hi,
it would be nice to have configurable space between workspace names. What I mean is in my case, when I am showing just programs icons in the name of the workspace, then sometimes it could be hard to distinguish which program is on which workspace just by looking in i3status bar. Have configurable space between i3wm workspaces, would help a lot.

Please look at attached image for better depiction of the feature: [https://imgur.com/a/qdslOAa](https://imgur.com/a/qdslOAa)

**Comment by orestisfl** [comment]
This does not belong to the i3status repo as i3bar (part of the main i3 [repo](https://github.com/i3/i3/)) draws those buttons, not i3status.

**Comment by bad63r** [comment]
Oh, ok. I'll adderss my request on that repo than.
