### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by DamienCassou** [i3/i3status#509]
The last release is more than a year old. Is it time to release again?

**Comment by 4nd3r** [comment]
Would love to see few PRs merged before that.

PRs I have been following:
#341 Add support for %bssid
#345 support pulse audio source (microphone)
#465 or #507 tztime format
#479 Custom battery %emptytime string when battery is full
#493 Port memory printing on OpenBSD
#511 introduce format_usage for cpu_usage

**Comment by feinedsquirrel** [comment]
I'd be happy to see a new release as well, specifically for battery idle from #486.

**Comment by DamienCassou** [comment]
Thank you very much.
