### ISSUE TITLE
Fix some issues with Ethernet status on FreeBSD

### ISSUE THREAD

**Issue by bsdjhb** [i3/i3status#56]
Sorry I don't have a pull request ready, but I committed a patch to FreeBSD's ports tree with various fixes for the Ethernet status on FreeBSD.  Here are the details from the commit message and a reference to the commit which includes the patch file:

https://svnweb.freebsd.org/ports?view=revision&revision=393973

Fix some nits with displaying Ethernet media status exposed by the recent
extended Ethernet media states:
- Don't apply IFM_SUBTYPE to the raw subtype in the description table.
  IFM_SUBTYPE() requires a fully populated word and was truncating values
  in the table when comparing resulting in false matches (notably
  "10GBase-KX4" for the no media case).
- Explicitly check for IFM_ETHER.
- Use SIOCGIFXMEDIA when present to obtain extended media states.
- Explicitly handle "no carrier".

**Comment by stapelberg** [comment]
Can you just send this as a pull request please? That makes merging so much easier.

**Comment by bsdjhb** [comment]
Done as request #58

**Comment by stapelberg** [comment]
Thanks!
