### ISSUE TITLE
Left angle bracket in module format breaks the module's block

### ISSUE THREAD

**Issue by raehik** [i3/i3status#6]
Log: http://logs.i3wm.org/logs/5649050225344512.bz2
Version: i3 version 4.9 (2015-02-28, branch "tags/4.9")

Putting a left angle bracket into the format of a block causes that block to not show up. Example (assuming volume is in the bar):

    volume master {
        format = "<%volume>"
    }

This used to show up as e.g. `...|<10%>|...`. I'm finding that it shows up as `...||...`.

I wasn't able to escape the left angle bracket with a backslash, so I assume it's not a new syntax feature. Found nothing relating to it in the [release notes](http://i3wm.org/downloads/RELEASE-NOTES-4.9.txt). Only *left* angle brackets broke the block -- right angle brackets made no difference. I could place it anywhere in the format and the same thing would happen.

Tested this on a system which hadn't upgraded to i3 v4.9. Worked before, broke immediately after I upgraded & restarted i3 in-place.

**Comment by stapelberg** [comment]
I think this is https://github.com/i3/i3/commit/b9cc54f15b23f3f0d5dc1ff066785fc4589faadf

@acrisci, can you clarify how users can escape angle brackets for pango please?

**Comment by acrisci** [comment]
Use `&lt;` like html.

I'll make a bug with pango and see if I can fix this.

**Comment by raehik** [comment]
Thanks, `&lt;` works for now.

**Comment by stapelberg** [comment]
In addition to escaping, we’ve reverted the default behavior to not use pango markup by default in i3 v4.10. Hence, I’m closing this issue.
