### ISSUE TITLE
Potential covert bug in the "with" macro

### ISSUE THREAD

**Issue by JSmith-BitFlipper** [i3/i3status#61]
Looking through some of the source of this project, I stumbled on a potential bug in i3status.h. The macro "with" (line 58) that is used to define a variable without a new scope has a potential hidden bug.

The code is as follows:
`#define with(type, var, init) \`
`for (type var = (type)-1; (var == (type)-1) && ((var = (init)) || 1);)`

This little "hack" would end up in an infinite loop if called like so: `with(int, i, -1);`
Although unlikely, it is still a hidden bug.

The following is a recommendation to what that like should be changed to, of course not unless there is some vulnerability or other bug that sprouts from it that I am unaware of. After the first pass, var will be assigned a value that will be guaranteed to fail the first predicate in the condition area of the for loop.
`#define with(type, var, init) \`
`for (type var = (type)-1; (var == (type)-1) && ((var = (init)) || 1); var = (type)1)`

Looking even deeper again :smile:, there is a bug that may arise if used irresponsibly. With the call `with(int, *i, <some address>)`, it is clear that a segmentation fault will occur during execution after being a pointer variable initialized to -1 and then have its value peeked in the condition `var == (type)-1` as `var` will expand to the dereference form which will explode in a segmentation fault. Though that is only if used irresponsibly, which should be avoided.

**Comment by Airblader** [comment]
I'm going to close this as it's not an actual issue. I'm sure improving this doesn't hurt, so please just send a pull request for it. :)
