### ISSUE TITLE
Error: status_command process exited unexpectedly (exit 1)

### ISSUE THREAD

**Issue by oberon2007** [i3/i3status#64]
As of yesterday in freshly created live-ISOs for Manjaro Linux i3status fails with the above error. Strangely, the finished install with the same configs works fine. Using the custom .i3/config and freshly installing i3status-git with yaourt also does not fix it.
Please let me know what useful information I can provide.
Using i3-wm-4.10.4

**Comment by oberon2007** [comment]
Trying to launch i3status from the terminal gives `# i3status
Could not set locale. Please make sure all your LC_* / LANG settings are correct.`

**Comment by oberon2007** [comment]
Ok. Getting somewhere. Seems to be a problem at our end...
```
# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by oberon2007** [comment]
Which variables is it looking for? LANG is also ok.
```# echo $LANG
en_US.UTF-8
```

**Comment by Airblader** [comment]
You mentioned in the Manjaro forums that a downgrade to old versions doesn't fix it so it's an environment issue. Hence I'll close this issue here. Sorry I made you report it here first just to close it again :)

**Comment by oberon2007** [comment]
Could you still help me with this? https://github.com/i3/i3status/issues/64#issuecomment-142920552
It would be very helpful to know why the error occurs - meaning, which variable needs to be defined to make i3status happy? As you can see most of them are fine: https://github.com/i3/i3status/issues/64#issuecomment-142922660
Is it obligatory to define LC_ALL= in order for i3status to be able to launch?

**Comment by Airblader** [comment]
Oh, alright. I'll reopen for now. I'm at the airport right now. Can you grep in the source code for "LC_"?

**Comment by oberon2007** [comment]
Thanks :) I have just double checked: All the undifined variables mentioned above are still undefined in the final install. So my burning question now is, what's missing? ;)

**Comment by Airblader** [comment]
@oberon2007 The relevant code in i3status is this:

````
   if (setlocale(LC_ALL, "") == NULL)                                                                                  
        die("Could not set locale. Please make sure all your LC_* / LANG settings are correct.");
```

According to the man page:

> On startup of the main program, the portable "C" locale is selected as default. A program may be made portable to all locales by calling:
>           setlocale(LC_ALL, "");

**Comment by oberon2007** [comment]
How can I solve this? Should I export LC_ALL=C ?
I don't understand why this is not a problem in the final install where LC_ALL remains undefined.
```
$ echo $LC_ALL

```

**Comment by Airblader** [comment]
The problem isn't that it's undefined, the problem is that i3status' request to change it fails. I don't know why, that's what has to be investigated now.

**Comment by oberon2007** [comment]
Thank you very much. I have an idea maybe ... ;) Thank you very much for your help!

**Comment by oberon2007** [comment]
We were able to fix it. https://github.com/manjaro/manjaro-tools/issues/145 Thank you again :)

**Comment by Airblader** [comment]
Glad to hear it :)

**Comment by loriezn** [comment]
Hi there i'm experiencing the same problem and the last link to the solution is dead. 

Would you be able to kindly point me in the right direction to figure this out please.
I'm scratching my head over it.
Much thanks and beer

**Comment by loriezn** [comment]
Sorry never mind! but here's a couple :beers: for your work anyways :-)

**Comment by oberon2007** [comment]
Ah I see, the issues have been removed from **manjaro-tools**.
For us the problem was just caused by not running ``locale-gen`` during ISO build. So we [reverting the commit](https://github.com/manjaro/manjaro-tools/commit/2259e083d85a93e1b5c7978780f2b2e96a7af696) that had removed the command.
Hope that helps :wink:
