### ISSUE TITLE
link quality allways @100%

### ISSUE THREAD

**Issue by StefaBa** [i3/i3status#74]
My Wifi Quality was stuck at 100% signal strength.
I found a signed with unsigned integer division which seems to be the culprit.
(introduced in 668bf2079f30e5df8f78974ebee2194d873f50ac)

couldn't attach patch, so here's the plaintext:

diff --git a/src/print_wireless_info.c b/src/print_wireless_info.c
index cd95562..f70d47d 100644
--- a/src/print_wireless_info.c
+++ b/src/print_wireless_info.c
@@ -100,7 +100,7 @@ static void print_bitrate(char *buffer, int buflen, int bitrate) {
     snprintf(buffer, buflen, "%g %cb/s", rate / divisor, scale);
 }
 
-static uint32_t nl80211_xbm_to_percent(int32_t xbm, uint32_t divisor) {
+static uint32_t nl80211_xbm_to_percent(int32_t xbm, int32_t divisor) {
 #define NOISE_FLOOR_DBM -90
 #define SIGNAL_MAX_DBM -20

**Comment by Airblader** [comment]
Can you send it as a pull request, please? That way if it gets merged you will be correctly attributed the contribution.

**Comment by StefaBa** [comment]
done.
Didn't really see it necessary as all i did was delete a single character in order to fix it. :)

**Comment by Airblader** [comment]
A fix is a fix, plus a bugfix usually (and in this case) also comes with the debugging work. :)
