### ISSUE TITLE
PulseAudio plugin: volume percentage is not rounded

### ISSUE THREAD

**Issue by lahwaacz** [i3/i3status#75]
Because of [this line](https://github.com/i3/i3status/blob/master/src/pulse.c#L81), the volume percentage shown by i3status is almost always off by 1% compared to other tools. What is wrong with doing float division and rounding to the nearest int value?

```c
int vol_perc = roundf( (float)avg_vol * 100 / PA_VOLUME_NORM );
```

**Comment by Watcom** [comment]
I haven't noticed that before but I can confirm now that pacmd reports it off by 1% as you describe. Can you submit a pull request?
