### ISSUE TITLE
Release tarballs on github produce empty version information

### ISSUE THREAD

**Issue by sur5r** [i3/i3status#78]
After finding out about https://github.com/i3/i3/issues/1993 I checked i3status as well. While building does not fail here, we end up with

    $ ./i3status --version
    i3status  () © 2008-2012 Michael Stapelberg and contributors

**Comment by eplanet** [comment]
I can confirm that issue. However, I see no easy fix, since the version is extracted during [make phase](https://github.com/i3/i3status/blob/master/Makefile#L28) from this git command:
```bash
VERSION:=$(shell git describe --tags --abbrev=0)
```
Maybe we could add a default value for the VERSION, like "latest" ? @stapelberg what do you think ?

**Comment by Airblader** [comment]
> Maybe we could add a default value for the VERSION, like "latest" ?

But that'd just be a lie since release tarballs are far from "latest".

Any reason we can't use the same approach as for i3?

**Comment by stapelberg** [comment]
We should definitely use the i3 solution for i3status (and i3lock, FWIW) as well.

**Comment by eplanet** [comment]
@Airblader, yeah well, you get the idea, "latest" was just an example…

i3 approach seems reasonable but implies to update LAST_VERSION root file for each pushed tag, it gets complicated just to handle this case.

**Comment by Airblader** [comment]
> yeah well, you get the idea, "latest" was just an example…

Even something like "unknown" (read: anything static) is bad because if the user reports a bug, there's no way of knowing which version they have installed.

> i3 approach seems reasonable but implies to update LAST_VERSION root file for each pushed tag, it gets complicated just to handle this case.

We don't release often, i3status even much more rarely than i3, so I don't see an issue with that. For i3 this is even scripted.
