### ISSUE TITLE
i3status no longer handles volumes greater than 100%

### ISSUE THREAD

**Issue by y2kbugger** [i3/i3status#79]
it used to display this just fine. with the last update that I did the volume still adjust properly above 100% still. but it display 100%

i3 version 4.11 (2015-09-30, branch "4.11")

http://logs.i3wm.org/logs/5077991642103808.bz2

not sure if this is due to a change in pulse audio, or  i3status.

**Comment by Watcom** [comment]
I'm unable to reproduce this, still getting the volume past 100%. I'm using PulseAudio 5 though.

**Comment by y2kbugger** [comment]
I just upgraded to PA 7. I'll put in a ticket there.

**Comment by y2kbugger** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=92635

**Comment by stapelberg** [comment]
Thanks for filing that upstream bug. I’ll close this report, please re-open if it turns out that it is an issue in i3status after all.
