### ISSUE TITLE
i3status says "No battery" 

### ISSUE THREAD

**Issue by StephanMeijer** [i3/i3status#80]
`i3status` displays `No battery`, while `acpi` displays that there is a battery plugged in (and there actually is).

`i3status --version` displays `i3status 2.9 (2015-03-22) © 2008-2012 Michael Stapelberg and contributors`

`i3status` displays:
```
i3status: trying to auto-detect output_format setting
i3status: auto-detected "term"
no IPv6 | 144.3 GiB | DHCP: yes | VPN: no | W: (046% at Burchtridder) 192.168.178.21 | E: down | No battery | 0.04 | 2015-10-27 09:09:55
```

`acpi` displays `Battery 0: Charging, 8%, 00:39:05 until charged`

**Comment by Airblader** [comment]
Do you have the right path set to your battery in the i3status config?

**Comment by jirimedved** [comment]
I have the path for example -> path = "/sys/class/power_supply/BAT1/uevent"

**Comment by Airblader** [comment]
Well, is it the correct path? Does it exist? Or should it read `…/BAT0/…`?

**Comment by StephanMeijer** [comment]
I'm sorry for my late response.

Correct path to my `uevent`-file is `/sys/class/power_supply/C239/uevent`. After editing file `$HOME/.i3status.conf` and setting the path, `i3status` seems recognize my battery.

I'm sorry I wasted your time with asking why it did not work. Thanks for your help.
