### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by moritzheiber** [i3/i3status#84]
I am bitten by [a particular "bug" in the wireless module of i3status](https://github.com/i3/i3status/commit/9e6e0d4f8f006a4aa897cb98868c22515d80ea1c) and would love to see a new release so that I can get reliable bandwidth information back :)

How about it?

**Comment by Airblader** [comment]
You can also just compile and install from source in the meantime. As soon as your package is updated in the repo, it will replace the custom install.

**Comment by moritzheiber** [comment]
@Airblader Absolutely, I just wanted to know whether I needed to invest the time to compile it on my own or whether there might be a release looming on the horizon :)

**Comment by stapelberg** [comment]
i3status release are a bit more involved because they aren’t automated (yet?). I’m not sure when the next one will happen and don’t have concrete plans. I’ll add a note to maybe look into it this weekend, but can’t promise anything.

**Comment by moritzheiber** [comment]
Anything's appreciated. Thanks! :heart:

**Comment by moritzheiber** [comment]
Woo, new release. Thanks!

**Comment by stapelberg** [comment]
You’re welcome, and sorry for it taking so long :).
