### ISSUE TITLE
i3status says 40% battery when acpitool says 57%

### ISSUE THREAD

**Issue by matthiasbeyer** [i3/i3status#87]
```
$ acpi
Battery 0: Discharging, 57%, 02:45:08 remaining
```

i3status says 40,18%, 2:55 h remaining.

10 minutes is not much, I don't care about this, but why is there a difference in the percentage? 

relevant config:
```
battery 0 {
    format = " %status %percentage <> %remaining -> %emptytime "
    format_down = "No battery"
    path = "/sys/class/power_supply/BAT%d/uevent"
    low_threshold = 10
}
```

**Comment by stapelberg** [comment]
Did you read http://i3wm.org/i3status/manpage.html#_battery? Does changing `last_full_capacity` make the output show what you expect it to?

**Comment by matthiasbeyer** [comment]
Yep, that fixes my issue. Should've read more carefully, sorry for bothering you.
