### ISSUE TITLE
arch linux i3:status_command process exited unexpectedly (exit 0)

### ISSUE THREAD

**Issue by avadakadevra** [i3/i3status#92]
i get this message in i3bar
status_command process exited unexpectedly (exit 0)
log is here
i3 version 4.11

http://logs.i3wm.org/logs/5642684278505472.bz2
[5642684278505472.zip](https://github.com/i3/i3status/files/84145/5642684278505472.zip)

**Comment by avadakadevra** [comment]
output of $i3status
===================
![i3status](https://cloud.githubusercontent.com/assets/13030646/12222224/e6beb114-b7d7-11e5-9c79-acc844f75394.jpg)

output of $sudo i3status
==========================
![sudoi3status](https://cloud.githubusercontent.com/assets/13030646/12222228/f61fc36e-b7d7-11e5-86f9-b06e830ffc0a.jpg)
sys info
=========
![sysinfo](https://cloud.githubusercontent.com/assets/13030646/12222229/0334c39c-b7d8-11e5-89b9-30106736ce93.jpg)

**Comment by stapelberg** [comment]
Which version of i3status is this? Can you reproduce it with https://aur.archlinux.org/packages/i3status-git/?

**Comment by avadakadevra** [comment]
replaced i3status with i3status-git (AUR)
out put of $i3status
=====================
![i3status-git](https://cloud.githubusercontent.com/assets/13030646/12222330/2fe3d2c2-b7db-11e5-9fbf-0b83273be983.jpg)
output of $sudo i3status
=========================
![sudoi3status-git](https://cloud.githubusercontent.com/assets/13030646/12222332/3ee05660-b7db-11e5-9dc9-8b0e8543e7da.jpg)

**Comment by avadakadevra** [comment]
i dont know why it says
*i3status: trying to autodetect output_format setting*
*i3status: auto-detected "term"*

output_format is set to "i3bar" in ~/.i3status.conf

**Comment by stapelberg** [comment]
It says that because you’re using `sudo`, hence `~/.i3status.conf` resolves to `/root/.i3status.conf`.

What happens when you run `i3status -c /etc/i3status.conf`? Can you attach your `.i3status.conf`? Also, can you provide a backtrace of the segmentation fault? Use `ulimit -c unlimited` before starting i3status, then run `gdb $(which i3status) core` and provide the output of the `backtrace full` command.

**Comment by avadakadevra** [comment]
**i3status -c /etc/i3status.conf** produces the same output as **sudo i3status**
my ~/.i3status.conf is here
[.i3status.conf.zip](https://github.com/i3/i3status/files/84191/default.i3status.conf.zip)

**Comment by stapelberg** [comment]
1. Can you comment out “order” lines from `~/.i3status.conf` until it no longer segfaults, then let us know which line causes the problem?

2. Can you try running `gdb i3status`, then `run`, then `backtrace full`?

**Comment by avadakadevra** [comment]
![gdb](https://cloud.githubusercontent.com/assets/13030646/12223624/3c800352-b7fe-11e5-865e-91ab7263ea62.jpg)

**Comment by avadakadevra** [comment]
problem solved. i commented out "order" lines from ~/.i3status.conf as you suggested. Then tested them out one at a time.
Problem was with the disk order. there was a typo in /home/(username).... corrected the mistake and it is working fine now
![i3bar](https://cloud.githubusercontent.com/assets/13030646/12223693/ae9a7890-b7ff-11e5-81a0-cff2b3e75877.jpg)

**Comment by avadakadevra** [comment]
thanks a lot

**Comment by Airblader** [comment]
There should not be a segfault, though. So we can still improve here.

**Comment by avadakadevra** [comment]
@Airblader 
my username is "faisal"
while "disk" order in ~/.i3status.conf was refrencing */home/faisals*
[.i3status.conf.zip](https://github.com/i3/i3status/files/85157/default.i3status.conf.zip)
correcting it to */home/faisal* solved the issue

**Comment by Airblader** [comment]
Yes, I understand. But i3status shouldn't segfault because of a wrong path.

**Comment by stapelberg** [comment]
Hm, I can’t reproduce this. With the following patch, running `./i3status -c i3status.conf` does not segfault, and valgrind doesn’t show any memory errors either:

```diff
--- i/i3status.conf
+++ w/i3status.conf
@@ -12,7 +12,7 @@ general {
 }
 
 order += "ipv6"
-order += "disk /"
+order += "disk /does/not/exist"
 order += "run_watch DHCP"
 order += "run_watch VPN"
 order += "wireless _first_"
```

**Comment by stapelberg** [comment]
Ah, in order to reproduce it, the disk block actually needs to be configured, i.e.:

```diff
--- i/i3status.conf
+++ w/i3status.conf
@@ -12,7 +12,7 @@ general {
 }
 
 order += "ipv6"
-order += "disk /"
+order += "disk /does/not/exist"
 order += "run_watch DHCP"
 order += "run_watch VPN"
 order += "wireless _first_"
@@ -52,6 +52,6 @@ load {
         format = "%1min"
 }
 
-disk "/" {
+disk "/does/not/exist" {
         format = "%avail"
 }
```

**Comment by privatefound** [comment]
i have the same problem but it don't work with disk fix

**Comment by GiovanniSM20** [comment]
me too @privatefound
