### ISSUE TITLE
i3status 2.10 doesn't refresh when sent SIGUSR1

### ISSUE THREAD

**Issue by rpls** [i3/i3status#93]
As the title says, the refresh doesn't work anymore for me. I'm using the Ubuntu wily and the stable repo mentioned on i3wm.org. But I can also reproduce the bug with a version I built from source.

How can I go about debugging this?

**Comment by stapelberg** [comment]
I think this broke because commit 1710c206 switched from nanosleep (interruptable by signals) to `pthread_cond_timedwait`, which needs to be interrupted explicitly.

**Comment by rpls** [comment]
So basically extend the `sigusr1` method with `pthread_cond_broadcast(&pthread_cond_broadcast);` instead of the empty method?
