### ISSUE TITLE
i3status---input in flex scanner failed

### ISSUE THREAD

**Issue by yanboyang713** [i3/i3status#98]
I have got problem with i3status. when I input i3status in terminal. it show that  input in flex scanner failed.
[yanboyang@archlinux config]$ i3status
input in flex scanner failed
when I use 
gdb to debug it
it show 
Starting program: /usr/bin/i3status 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
input in flex scanner failed
[Inferior 1 (process 5506) exited with code 02]
do you know how to solve this problem

**Comment by stapelberg** [comment]
Your config file might be broken. Can you please provide the following files?

* `~/.i3status.conf`
* `~/.config/i3status/config`
* `$XDG_CONFIG_HOME/i3status/config`
* `/etc/i3status.conf`

**Comment by yanboyang713** [comment]
this is my config file http://pastebin.com/0L760NeZ

**Comment by stapelberg** [comment]
That file works for me. Can you run `strace -f -o /tmp/strace.log -s 2048 -v -tt i3status`, then provide the resulting `/tmp/strace.log`?

**Comment by yanboyang713** [comment]
This is strace.log
http://pastebin.com/T90jsS0w

**Comment by stapelberg** [comment]
From the log:

```
10673 11:05:23.133368 open("/home/yanboyang/.config/i3status/config", O_RDONLY) = 3
10673 11:05:23.133433 ioctl(3, TCGETS, 0x7ffe082ce2d0) = -1 ENOTTY (Inappropriate ioctl for device)
10673 11:05:23.133496 fstat(3, {st_dev=makedev(8, 3), st_ino=1054357, st_mode=S_IFDIR|0755, st_nlink=2, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=2014/11/14-00:47:37, st_mtime=2016/01/17-10:01:12, st_ctime=2016/01/17-10:01:12}) = 0
10673 11:05:23.133563 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6b95e8e000
10673 11:05:23.133610 read(3, 0xe386d0, 8192) = -1 EISDIR (Is a directory)
```

So, `/home/yanboyang/.config/i3status/config` is expected to be a config file, but on your machine, it seems to be a directory. Once you address that, i3status should work.

**Comment by yanboyang713** [comment]
Hi stapelberg, Thank you so much. config is file not directory, right? Can I change /home/yanboyang/.config/i3status/config to point a file?

**Comment by stapelberg** [comment]
I don’t quite understand the question. The intended state is that `cat ~/.config/i3status/config` will print a configuration file, not the error message `cat: config: Is a directory`.

**Comment by yanboyang713** [comment]
ok, understand. Thanks
